// Module included in the following assemblies:
//
// * serverless/develop/serverless-apiserversource.adoc
// * serverless/reference/kn-eventing-ref.adoc

:_content-type: PROCEDURE
[id="apiserversource-kn_{context}"]
= 使用 Knative CLI 创建 API 服务器源

您可以使用  `kn source apiserver create` 命令，使用 `kn` CLI 创建 API 服务器源。使用 kn CLI 创建 API 服务器源可提供比直接修改 YAML 文件更精简且直观的用户界面。

.先决条件

* 在集群中安装了 {ServerlessOperatorName} 和 Knative Eventing。
* 您已创建了一个项目，或者具有适当的角色和权限访问项目，以便在 {product-title} 中创建应用程序和其他工作负载。
* 已安装 Uccps CLI (`oc`).
* 已安装 Knative (`kn`) CLI.

.流程

include::snippets/serverless-service-account-apiserversource.adoc[]

. 创建具有事件 sink 的 API 服务器源。在以下示例中，sink 是一个代理：
+
[source,terminal]
----
$ kn source apiserver create <event_source_name> --sink broker:<broker_name> --resource "event:v1" --service-account <service_account_name> --mode Resource
----
// need to revisit these docs and give better tutorial examples with different sinks; out of scope for the current PR

. 要检查 API 服务器源是否已正确设置，请创建一个 Knative 服务，在日志中转储传入的信息：
+
[source,terminal]
----
$ kn service create <service_name> --image quay.io/openshift-knative/knative-eventing-sources-event-display:latest
----

. 如果您使用代理作为事件 sink，请创建一个触发器将事件从 default 代理过滤到服务：
+
[source,terminal]
----
$ kn trigger create <trigger_name> --sink ksvc:<service_name>
----

. 通过在 default 命名空间中启动 pod 来创建事件：
+
[source,terminal]
----
$ oc create deployment hello-node --image quay.io/openshift-knative/knative-eventing-sources-event-display:latest
----

. 通过检查以下命令生成的输出来检查是否正确映射了控制器：
+
[source,terminal]
----
$ kn source apiserver describe <source_name>
----
+
.输出示例
[source,terminal]
----
Name:                mysource
Namespace:           default
Annotations:         sources.knative.dev/creator=developer, sources.knative.dev/lastModifier=developer
Age:                 3m
ServiceAccountName:  events-sa
Mode:                Resource
Sink:
  Name:       default
  Namespace:  default
  Kind:       Broker (eventing.knative.dev/v1)
Resources:
  Kind:        event (v1)
  Controller:  false
Conditions:
  OK TYPE                     AGE REASON
  ++ Ready                     3m
  ++ Deployed                  3m
  ++ SinkProvided              3m
  ++ SufficientPermissions     3m
  ++ EventTypesProvided        3m
----

.验证

您可以通过查看消息转储程序功能日志来验证 Kubernetes 事件是否已发送到 Knative。

. 获取 pod:
+
[source,terminal]
----
$ oc get pods
----

. 查看 pod 的消息转储程序功能日志：
+
[source,terminal]
----
$ oc logs $(oc get pod -o name | grep event-display) -c user-container
----
+
.输出示例
[source,terminal]
----
☁️  cloudevents.Event
Validation: valid
Context Attributes,
  specversion: 1.0
  type: dev.knative.apiserver.resource.update
  datacontenttype: application/json
  ...
Data,
  {
    "apiVersion": "v1",
    "involvedObject": {
      "apiVersion": "v1",
      "fieldPath": "spec.containers{hello-node}",
      "kind": "Pod",
      "name": "hello-node",
      "namespace": "default",
       .....
    },
    "kind": "Event",
    "message": "Started container",
    "metadata": {
      "name": "hello-node.159d7608e3a3572c",
      "namespace": "default",
      ....
    },
    "reason": "Started",
    ...
  }
----

.输出示例

. 删除触发器：
+
[source,terminal]
----
$ kn trigger delete <trigger_name>
----

. 删除事件源：
+
[source,terminal]
----
$ kn source apiserver delete <source_name>
----

. 删除服务帐户、集群角色和集群绑定：
+
[source,terminal]
----
$ oc delete -f authentication.yaml
----
