// Module included in the following assemblies:
//
// * builds/creating-build-inputs.adoc

:_content-type: PROCEDURE
[id="builds-automatically-add-source-clone-secrets_{context}"]
= 自动把源克隆 secret 添加到构建配置

创建 `BuildConfig`，统信容器云管理平台 可以自动填充其源克隆 secret 引用。这会使生成的构建自动使用存储在引用的 secret 中的凭证与远程 Git 存储库进行身份验证，而无需进一步配置。

若要使用此功能，包含 Git 存储库凭证的一个 secret 必须存在于稍后创建 `BuildConfig` 的命名空间中。此 secret 必须包含前缀为 `build.openshift.io/source-secret-match-uri-` 的一个或多个注解。这些注解中的每一个值都是统一资源标识符（URI）模式，其定义如下。如果 BuildConfig 是在没有源克隆 secret 引用的前提下创建的，并且其 Git 源 URI 与 secret 注解中的 URI 模式匹配，统信容器云管理平台 将自动在 `BuildConfig` 插入对该 secret 的引用。

.先决条件

URI 模式必须包含：

* 有效的方案包括： `*://`, `git://`, `http://`, `https://` or `ssh://`
* 一个主机： \*` or a valid hostname or IP address optionally preceded by `*.`
* 一个路径： `/\*` or `/` followed by any characters optionally including `*` characters

在上述所有内容中，`*` 字符被认为是通配符。

[重要]
====
URI 模式必须与符合 RFC3986 的 Git 源 URI 匹配。不要在 URI 模式中包含用户名（或密码）组件。

例如，如果使用 `ssh://git@bitbucket.atlassian.com:7999/ATLASSIAN jira.git` 作为 git 存储库 URL，则源 secret 必须指定为 `ssh://bitbucket.atlassian.com:7999/*`（而非 `ssh://git@bitbucket.atlassian.com:7999/*`）。

[source,terminal]
----
$ oc annotate secret mysecret \
    'build.openshift.io/source-secret-match-uri-1=ssh://bitbucket.atlassian.com:7999/*'
----

====

.流程

如果多个 secret 与特定 `BuildConfig` 的 Git URI 匹配，统信容器云管理平台 会选择匹配最多的 secret。这可以实现下例中所示的基本覆盖。

以下片段显示了两个部分源克隆 secret，第一个匹配通过 HTTPS 访问的 `mycorp.com` 域中的任意服务器，第二个则覆盖对服务器 `mydev1.mycorp.com` 和 `mydev2.mycorp.com` 的访问：

[source,yaml]
----
kind: Secret
apiVersion: v1
metadata:
  name: matches-all-corporate-servers-https-only
  annotations:
    build.openshift.io/source-secret-match-uri-1: https://*.mycorp.com/*
data:
  ...
---
kind: Secret
apiVersion: v1
metadata:
  name: override-for-my-dev-servers-https-only
  annotations:
    build.openshift.io/source-secret-match-uri-1: https://mydev1.mycorp.com/*
    build.openshift.io/source-secret-match-uri-2: https://mydev2.mycorp.com/*
data:
  ...
----

* 使用以下命令将 `build.openshift.io/source-secret-match-uri-` 注解添加到预先存在的 secret：
+
[source,terminal]
----
$ oc annotate secret mysecret \
    'build.openshift.io/source-secret-match-uri-1=https://*.mycorp.com/*'
----
