// Module included in the following assemblies:
//
// * builds/creating-build-inputs.adoc

[id="builds-image-source_{context}"]
= 镜像源

您可以使用镜像向构建过程添加其他文件。输入镜像的引用方式与定义 `From` 和 `To` 镜像目标的方式相同。这意味着可以引用容器镜像和镜像流标签。在使用镜像时，必须提供一个或多个路径对，以指示要复制镜像的文件或目录的路径以及构建上下文中要放置它们的目的地。

源路径可以是指定镜像内的任何绝对路径。目的地必须是相对目录路径。构建时会加载镜像，并将指定的文件和目录复制到构建过程上下文目录中。这与源存储库内容要克隆到的目录相同。如果源路径以 `/.` 结尾，则复制目录的内容，但不在目的地上创建该目录本身。

镜像输入在 `BuildConfig` 的 `source` 定义中指定：

[source,yaml]
----
source:
  git:
    uri: https://github.com/openshift/ruby-hello-world.git
    ref: "master"
  images: <1>
  - from: <2>
      kind: ImageStreamTag
      name: myinputimage:latest
      namespace: mynamespace
    paths: <3>
    - destinationDir: injected/dir <4>
      sourcePath: /usr/lib/somefile.jar <5>
  - from:
      kind: ImageStreamTag
      name: myotherinputimage:latest
      namespace: myothernamespace
    pullSecret: mysecret <6>
    paths:
    - destinationDir: injected/dir
      sourcePath: /usr/lib/somefile.jar
----
<1> 由一个或多个输入镜像和文件组成的数组。
<2> 对包含要复制的文件的镜像的引用。
<3> 源/目标路径的数组。
<4> 相对于构建过程能够处理文件的构建根目录的目录。
<5> 要从所引用镜像中复制文件的位置。
<6> 提供的可选 `secret`，如需要凭证才能访问输入镜像。
+
[注意]
====
如果您的集群使用 `ImageContentSourcePolicy` 对象来配置存储库镜像，则只能将全局 pull secret 用于镜像 registry。您不能在项目中添加 pull secret。
====

另外，如果输入镜像需要 pull secret，您可以将 pull secret 链接到构建所使用的服务帐户。默认情况下，构建使用 `builder` 服务帐户。如果 secret 包含与托管输入镜像的存储库匹配的凭证，pull secret 会自动添加到构建中。要将 pull secret 连接到构建使用的服务帐户，请运行：

[source,terminal]
----
$ oc secrets link builder dockerhub
----

[注意]
====
使用自定义策略的构建不支持此功能。
====

/////
[role="_additional-resources"]
.Additional resources

* Custom Strategy
ifndef::openshift-online[]
* ImageStreamTags
endif::[]
/////
