// Module included in the following assemblies:
//
// * cicd/builds/creating-build-inputs.adoc
// * cicd/builds/builds-using-build-volumes.adoc

:_module-type: PROCEDURE

:_content-type: PROCEDURE
[id="builds-adding-input-secrets-configmaps_{context}"]
= 添加输入 secret 和配置映射

[role="_abstract"]
要向构建提供凭证和其他配置数据，而不将其放在源控制中，您可以定义输入 secret 和输入配置映射。

在某些情况下，构建操作需要凭证或其他配置数据才能访问依赖的资源。要使该信息在不置于源控制中的情况下可用，您可以定义输入 secret 和输入配置映射。

.流程

将输入 secret 和配置映射添加到现有的 `BuildConfig` 对象中：

. 如果 `ConfigMap` 对象不存在，则进行创建：
+
[source,terminal]
----
$ oc create configmap settings-mvn \
    --from-file=settings.xml=<path/to/settings.xml>
----
+
这会创建一个名为 `settings-mvn` 的新配置映射，其中包含 `settings.xml` 文件的纯文本内容。
+
[提示]
====
您还可以应用以下 YAML 来创建配置映射：
[source,yaml]
----
apiVersion: core/v1
kind: ConfigMap
metadata:
  name: settings-mvn
data:
  settings.xml: |
    <settings>
    … # Insert maven settings here
    </settings>
----
====


. 如果 `Secret` 对象不存在，则进行创建：
+
[source,terminal]
----
$ oc create secret generic secret-mvn \
    --from-file=id_rsa=<path/to/.ssh/id_rsa>
    --type=kubernetes.io/ssh-auth
----
+
这会创建一个名为 `secret-mvn` 的新 secret，其包含 `id_rsa` 私钥的 base64 编码内容。
+
[提示]
====
您还可以应用以下 YAML 来创建输入 secret：
[source,yaml]
----
apiVersion: core/v1
kind: Secret
metadata:
  name: secret-mvn
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: |
    # Insert ssh private key, base64 encoded
----
====

. 将配置映射和 secret 添加到现有 `BuildConfig` 对象的 `source` 部分中：
+
[source,yaml]
----
source:
  git:
    uri: https://github.com/wildfly/quickstart.git
  contextDir: helloworld
  configMaps:
    - configMap:
        name: settings-mvn
  secrets:
    - secret:
        name: secret-mvn
----

要在新 `BuildConfig` 对象中包含 secret 和配置映射，请运行以下命令：

[source,terminal]
----
$ oc new-build \
    openshift/wildfly-101-centos7~https://github.com/wildfly/quickstart.git \
    --context-dir helloworld --build-secret “secret-mvn” \
    --build-config-map "settings-mvn"
----

在构建期间，`settings.xml` 和 `id_rsa` 文件将复制到源代码所在的目录中。在 统信容器云管理平台 S2I 构建器镜像中，这是镜像的工作目录，使用 Dockerfile 中的 `WORKDIR` 指令设置。如果要指定其他目录，请在定义中添加 destinationDir：

[source,yaml]
----
source:
  git:
    uri: https://github.com/wildfly/quickstart.git
  contextDir: helloworld
  configMaps:
    - configMap:
        name: settings-mvn
      destinationDir: ".m2"
  secrets:
    - secret:
        name: secret-mvn
      destinationDir: ".ssh"
----

您还可以指定创建新 `BuildConfig` 对象时的目标目录：

[source,terminal]
----
$ oc new-build \
    openshift/wildfly-101-centos7~https://github.com/wildfly/quickstart.git \
    --context-dir helloworld --build-secret “secret-mvn:.ssh” \
    --build-config-map "settings-mvn:.m2"
----

在这两种情况下，`settings.xml` 文件都添加到构建环境的 `./.m2` 目录中，而 `id_rsa` 密钥则添加到 `./.ssh` 目录中。
