:_module-type: PROCEDURE

ifeval::["{context}" == "build-strategies-docker"]
:dockerstrategy:
endif::[]
ifeval::["{context}" == "build-strategies-s2i"]
:sourcestrategy:
endif::[]


:_content-type: PROCEDURE
[id="builds-using-build-volumes_{context}"]
= 使用构建卷

[role="_abstract"]
您可以挂载构建卷，为运行的构建授予您不想在输出容器镜像中保留的信息的访问权限。

构建卷提供仅在构建时需要的敏感信息，如存储库凭据。构建卷与构建输入不同，后者的数据可以保留在输出容器镜像中。

构建卷的挂载点（运行中的构建从中读取数据）在功能上与 pod 卷挂载 类似。

.先决条件
* 您已将输入 secret 和配置映射添加到 BuildConfig 对象中。

.Procedure

ifdef::dockerstrategy[]

* 在 `BuildConfig` 对象的 `dockerStrategy` 定义中，将任何构建卷添加到 `volumes` 数组中。例如：
+
[source,yaml]
----
spec:
  dockerStrategy:
    volumes:
      - name: secret-mvn <1>
        mounts:
        - destinationPath: /opt/app-root/src/.ssh <2>
        source:
          type: Secret <3>
          secret:
            secretName: my-secret <4>
      - name: settings-mvn <1>
        mounts:
        - destinationPath: /opt/app-root/src/.m2  <2>
        source:
          type: ConfigMap <3>
          configMap:
            name: my-config <4>
      - name: my-csi-volume <1>
        mounts:
        - destinationPath: /opt/app-root/src/some_path  <2>
        source:
          type: CSI <3>
          csi:
            driver: csi.sharedresource.openshift.io <5>
            readOnly: true <6>
            volumeAttributes: <7>
              attribute: value
----
<1> 必需。唯一的名称。
<2> 必需。挂载点的绝对路径。它不能包含 `..` 或 `:` 且不与构建器生成的目的地路径冲突。`/opt/app-root/src` 是许多支持 统信 S2I 的镜像的默认主目录。
<3> 必需。源类型，`ConfigMap`、`Secret` 或 `CSI`。
<4> 必需。源的名称。
<5> 必需。提供临时 CSI 卷的驱动程序。
<6> 可选。如果为 true，这指示驱动程序提供只读卷。
<7> 可选。临时 CSI 卷的卷属性。如需支持的属性键和值，请参阅 CSI 驱动程序的文档。

[注意]
====
共享资源 CSI 驱动程序作为技术预览提供。
====

endif::dockerstrategy[]

ifdef::sourcestrategy[]

* In the `sourceStrategy` definition of the `BuildConfig` object, add any build volumes to the `volumes` array. For example:
+
[source,yaml]
----
spec:
  sourceStrategy:
    volumes:
      - name: secret-mvn <1>
        mounts:
        - destinationPath: /opt/app-root/src/.ssh <2>
        source:
          type: Secret <3>
          secret:
            secretName: my-secret <4>
      - name: settings-mvn <1>
        mounts:
        - destinationPath: /opt/app-root/src/.m2 <2>
        source:
          type: ConfigMap <3>
          configMap:
            name: my-config <4>
      - name: my-csi-volume <1>
        mounts:
        - destinationPath: /opt/app-root/src/some_path  <2>
        source:
          type: CSI <3>
          csi:
            driver: csi.sharedresource.openshift.io <5>
            readOnly: true <6>
            volumeAttributes: <7>
              attribute: value
----

<1> Required. A unique name.
<2> Required. The absolute path of the mount point. It must not contain `..` or `:` and doesn't collide with the destination path generated by the builder. The `/opt/app-root/src` is the default home directory for many Red Hat S2I-enabled images.
<3> Required. The type of source, `ConfigMap`, `Secret`, or `CSI`.
<4> Required. The name of the source.
<5> Required. The driver that provides the ephemeral CSI volume.
<6> Optional. If true, this instructs the driver to provide a read-only volume.
<7> Optional. The volume attributes of the ephemeral CSI volume. Consult the CSI driver's documentation for supported attribute keys and values.

[NOTE]
====
The Shared Resource CSI Driver is supported as a Technology Preview feature.
====

endif::sourcestrategy[]

ifeval::["{context}" == "build-strategies-docker"]
:!dockerstrategy:
endif::[]
ifeval::["{context}" == "build-strategies-s2i"]
:!sourcestrategy:
endif::[]
