// Module included in the following assemblies:
//
// * builds/triggering-builds-build-hooks.adoc

:_content-type: PROCEDURE
[id="builds-using-image-change-triggers_{context}"]
= 使用镜像更改触发器

作为开发人员，您可以将构建配置为在每次基础镜像更改时自动运行。

当上游镜像有新版本可用时，您可以使用镜像更改触发器自动调用构建。例如，如果构建基于 RHEL 镜像，您可以触发该构建在 RHEL 镜像更改时运行。因此，应用程序镜像始终在最新的 RHEL 基础镜像上运行。

[注意]
====
指向 v1 容器 registry 中的容器镜像的镜像流仅在镜像流标签可用时触发一次构建，后续镜像更新时则不会触发。这是因为 v1 容器 registry 中缺少可唯一标识的镜像。
====

.流程

. 定义指向您要用作触发器的上游镜像的 `ImageStream` ：
+
[source,yaml]
----
kind: "ImageStream"
apiVersion: "v1"
metadata:
  name: "ruby-20-centos7"
----
+
这将定义绑定到位于 `<system-registry>/<namespace>/ruby-20-centos7` 的容器镜像存储库的镜像流。`<system-registry>` 定义为 统信容器云管理平台 中运行的名为 `docker-registry` 的服务。

. 如果镜像流是构建的基础镜像，请将构建策略中的 from 字段设置为指向 `ImageStream`：
+
[source,yaml]
----
strategy:
  sourceStrategy:
    from:
      kind: "ImageStreamTag"
      name: "ruby-20-centos7:latest"
----
+
在这种情形中，`sourceStrategy` 定义将消耗此命名空间中名为 `ruby-20-centos7` 的镜像流的 `latest` 标签。

. 使用指向 `ImageStreams` 的一个或多个触发器定义构建：
+
[source,yaml]
----
type: "ImageChange" <1>
imageChange: {}
type: "ImageChange" <2>
imageChange:
  from:
    kind: "ImageStreamTag"
    name: "custom-image:latest"
----
<1> 监控构建策略的 `from` 字段中定义的 `ImageStream` 和 `Tag` 的镜像更改触发器。此处的 `imageChange` 对象必须留空。
<2> 监控任意镜像流的镜像更改触发器。此时 imageChange 部分必须包含一个 `from` 字段，以引用要监控的 `ImageStreamTag`。

将镜像更改触发器用于策略镜像流时，生成的构建会获得一个不可变 docker 标签，指向与该标签对应的最新镜像。在执行构建时，策略会使用此新镜像引用。

对于不引用策略镜像流的其他镜像更改触发器，系统会启动新构建，但不会使用唯一镜像引用来更新构建策略。

由于此示例具有策略的镜像更改触发器，因此生成的构建将是：

[source,yaml]
----
strategy:
  sourceStrategy:
    from:
      kind: "DockerImage"
      name: "172.30.17.3:5001/mynamespace/ruby-20-centos7:<immutableid>"
----

这将确保触发的构建使用刚才推送到存储库的新镜像，并且可以使用相同的输入随时重新运行构建。

您可以暂停镜像更改触发器，以便在构建开始之前对引用的镜像流进行多次更改。在将 `ImageChangeTrigger` 添加到 `BuildConfig` 时，您也可以将 `paused` 属性设为 true，以避免立即触发构建。

[source,yaml]
----
type: "ImageChange"
imageChange:
  from:
    kind: "ImageStreamTag"
    name: "custom-image:latest"
  paused: true
----

除了设置适用于所有 Strategy 类型的镜像字段外，自定义构建还需要检查 `OPENSHIFT_CUSTOM_BUILD_BASE_IMAGE` 环境变量。如果不存在，则使用不可变镜像引用来创建它。如果存在，则使用不可变镜像引用进行更新。

如果因为 Webhook 触发器或手动请求而触发构建，则创建的构建将使用从 `Strategy` 引用的 `ImageStream` 解析而来的 `<immutableid>`。这将确保使用一致的镜像标签来执行构建，以方便再生。 

[role="_additional-resources"]
.其他资源

* link:http://docs.docker.com/v1.7/reference/api/hub_registry_spec/#docker-registry-1-0[v1 容器 registry]
