// Module included in the following assemblies:
//
// * nodes/nodes/node-health-check-operator-installation.adoc

:_content-type: PROCEDURE
[id="installing-node-health-check-operator-using-cli_{context}"]
= 使用 CLI 安装 Node Health Check Operator
您可以使用 Uccps CLI （oc）安装 Node Health Check Operator。

要在您自己的命名空间中安装 Operator，请按照以下步骤执行。

要在 `openshift-operators` 命名空间中安装 Operator，请跳至步骤 3，因为需要新的 `Namespace` 自定义资源(CR)和 OperatorGroup CR 的步骤。

.先决条件

* 安装 Uccps CLI (`oc`).
* 以具有  `cluster-admin` 特权的用户身份登录。

.流程

. 为 Node Health Check Operator 创建 `Namespace` 1.自定义资源 (CR)：
.. 定义 `Namespace` CR 并保存 YAML 文件，如  `node-health-check-namespace.yaml`:
+
[source,yaml]
----
apiVersion: v1
kind: Namespace
metadata:
  name: node-health-check
----
.. 要创建 `Namespace` CR，请运行以下命令：
+
[source,terminal]
----
$ oc create -f node-health-check-namespace.yaml
----

. 创建 `OperatorGroup` CR:
.. 定义 `OperatorGroup` CR 并保存 YAML 文件，如 `node-health-check-operator-group.yaml`:
+
[source,yaml]
----
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: node-health-check-operator
  namespace: node-health-check
----
.. 要创建 `OperatorGroup` CR，请运行以下命令：
+
[source,terminal]
----
$ oc create -f node-health-check-operator-group.yaml
----

. 创建一个 `Subscription` CR:
.. 定义 `Subscription` CR 并保存 YAML 文件，如  `node-health-check-subscription.yaml`:
+
[source,yaml]
----
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
    name: node-health-check-operator
    namespace: node-health-check <1>
spec:
    channel: candidate <2>
    installPlanApproval: Manual <3>
    name: node-healthcheck-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    package: node-healthcheck-operator
----
<1> 指定您要安装 Node Health Check Operator 的 `Namespace` 。要在 `openshift-operators` 命名空间中安装 Node Health Check Operator，请在 Subscription CR 中指定 `openshift-operators`
<2> 指定订阅的频道名称。要升级到 Node Health Check Operator 的最新版本，您必须手动将订阅的频道名称从 alpha 改为 candidate。
<3> 如果您的指定版本被目录中的后续版本取代，则将批准策略设置为 Manual。此计划阻止自动升级到更新的版本，且需要在启动 CSV 可以完成安装前手动批准。

.. 要创建 `Subscription`，请运行以下命令：
+
[source,terminal]
----
$ oc create -f node-health-check-subscription.yaml
----

.验证

. 检查 CSV 资源来验证安装是否成功：
+
[source,terminal]
----
$ oc get csv -n openshift-operators
----
+
.输出示例

[source,terminal]
----
NAME                              DISPLAY                     VERSION  REPLACES PHASE
node-healthcheck-operator.v0.2.0. Node Health Check Operator  0.2.0             Succeeded
----
. 验证 Node Health Check Operator 是否正在运行：
+
[source,terminal]
----
$ oc get deploy -n openshift-operators
----
+
.输出示例

[source,terminal]
----
NAME                                           READY   UP-TO-DATE   AVAILABLE   AGE
node-health-check-operator-controller-manager  1/1     1            1           10d
----
