// Module included in the following assemblies:
//
// * nodes/nodes/eco-poison-pill-operator.adoc

:_content-type: PROCEDURE
[id="installing-poison-pill-operator-using-cli_{context}"]
= 使用 CLI 安装 Poison Pill Operator

您可以使用 Uccps CLI (`oc`) 安装 Poison Pill Operator。

您可以在自己的命名空间中或 `openshift-operators` 命名空间中安装 Poison Pill Operator。

要在您自己的命名空间中安装 Operator，请按照以下步骤执行。

要在  `openshift-operators`  命名空间中安装 Operator，请跳至步骤 3，因为需要新的 `Namespace` 自定义资源(CR)和 `OperatorGroup` CR 的步骤。

.先决条件

* 安装 Uccps CLI (`oc`).
* 以具有 `cluster-admin` 特权的用户身份登录。

.流程

. 为 Poison Pill Operator 创建 `Namespace` 1.自定义资源(CR)：
.. 定义 `Namespace` CR 并保存 YAML 文件，如 `poison-pill-namespace.yaml`:
+
[source,yaml]
----
apiVersion: v1
kind: Namespace
metadata:
  name: poison-pill
----
.. 要创建 `Namespace` CR，请运行以下命令：
+
[source,terminal]
----
$ oc create -f poison-pill-namespace.yaml
----

. 创建 `OperatorGroup` CR:
.. 定义 `OperatorGroup` CR 并保存 YAML 文件，如  `poison-pill-operator-group.yaml`:
+
[source,yaml]
----
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: poison-pill-manager
  namespace: poison-pill
----
.. 要创建 `OperatorGroup` CR，请运行以下命令：
+
[source,terminal]
----
$ oc create -f poison-pill-operator-group.yaml
----

. 创建一个 `Subscription` CR:
.. 定义 `Subscription` CR 并保存 YAML 文件，如 `poison-pill-subscription.yaml`:
+
[source,yaml]
----
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
    name: poison-pill-manager
    namespace: poison-pill <1>
spec:
    channel: stable
    installPlanApproval: Manual <2>
    name: poison-pill-manager
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    package: poison-pill-manager
----
<1> 指定您要安装 Poison Pill Operator 的 `Namespace` 。要在 `openshift-operators` 命名空间中安装 Poison Pill Operator，请在 Subscription CR 中指定 `openshift-operators`。
<2> 如果您的指定版本被目录中的后续版本取代，则将批准策略设置为 Manual。此计划阻止自动升级到更新的版本，且需要在启动 CSV 可以完成安装前手动批准。

.. 要创建 `Subscription` ，请运行以下命令：
+
[source,terminal]
----
$ oc create -f poison-pill-subscription.yaml
----

.验证

. 检查 CSV 资源来验证安装是否成功：
+
[source,terminal]
----
$ oc get csv -n poison-pill
----
+
.输出示例
[source,terminal]
----
NAME                   DISPLAY                 VERSION   REPLACES    PHASE
poison-pill.v.0.2.0     Poison Pill Operator    0.2.0                 Succeeded
----

. 验证 Poison Pill Operator 是否正在运行：
+
[source,terminal]
----
$ oc get deploy -n poison-pill
----
+
.输出示例
[source,terminal]
----
NAME                                 READY   UP-TO-DATE   AVAILABLE   AGE
poison-pill-controller-manager       1/1     1            1           10d
----

. 验证 Poison Pill Operator 是否创建了 PoisonPillConfig CR：
+
[source,terminal]
----
$ oc get PoisonPillConfig -n poison-pill
----
+
.输出示例
[source,terminal]
----
NAME                 AGE
poison-pill-config   10d
----
. 验证每个就绪的 pill pod 是否已调度并在每个 worker 节点上运行：
+
[source,terminal]
----
$ oc get daemonset -n poison-pill
----
+
.输出示例
[source,terminal]
----
NAME             DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
poison-pill-ds   2         2         2       2            2           <none>          10d
----
+
[NOTE]
====
control plane 节点不支持这个命令。
====