:_content-type: PROCEDURE

[id="ephemeral-storage-using-a-sharedconfigmap-object-in-a-pod_{context}"]
= 在 pod 中使用 SharedConfigMap 实例

[role="_abstract"]
要从 pod 访问 `SharedConfigMap` 自定义资源(CR)实例，您需要授予给定服务帐户 RBAC 权限以使用该 `SharedConfigMap` CR 实例。

.先决条件

* 您已为要在集群中的命名空间间共享的配置映射创建了 `SharedConfigMap` CR 实例。
* 您必须具有执行以下操作的权限：
** 创建构建配置和启动构建。
** 输入 `oc get sharedconfigmaps` 命令并返回非空列表来发现哪些 `SharedConfigMap` CR 实例可用。
** 确定命名空间中的 builder 服务帐户是否可以使用给定的 `SharedSecret` CR 实例。也就是说，您可以运行 `oc adm policy who-can use <identifier of specific SharedSecret >` 来查看是否列出命名空间中的 builder 服务帐户。

[注意]
====
如果没有满足此列表中的最后两个先决条件，请创建或询问某人创建所需的基于角色的访问控制(RBAC)，以便您可以发现 `SharedConfigMap` CR 实例，并启用服务帐户使用 `SharedConfigMap` CR 实例。
====

.流程

. 通过使用 `oc apply` with YAML 内容，为给定服务帐户 RBAC 权限授予在其 pod 中使用 `SharedConfigMap` CR 实例的权限。
+
[注意]
====
目前，`kubectl` 和 oc 具有硬编码的特殊问题单逻辑，将 `use` 动词限制为围绕 pod 安全性而成的角色。因此，您无法使用 `oc create role …`​ 创建使用 `SharedConfigMap` CR 实例所需的角色。
====
+
[source,terminal]
----
$ oc apply -f - <<EOF
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: shared-resource-my-share
  namespace: my-namespace
rules:
  - apiGroups:
      - sharedresource.openshift.io
    resources:
      - sharedconfigmaps
    resourceNames:
      - my-share
    verbs:
      - use
EOF
----

. 使用 `oc` 命令创建与角色关联的 `RoleBinding` ：
+
[source,terminal]
----
oc create rolebinding shared-resource-my-share --role=shared-resource-my-share --serviceaccount=my-namespace:builder
----

. 从 pod 访问 `SharedConfigMap` CR 实例：
+
[source,terminal]
----
$ oc apply -f - <<EOF
kind: Pod
apiVersion: v1
metadata:
  name: my-app
  namespace: my-namespace
spec:
  serviceAccountName: default

# containers omitted …. Follow standard use of ‘volumeMounts’ for referencing your shared resource volume

    volumes:
    - name: my-csi-volume
      csi:
        readOnly: true
        driver: csi.sharedresource.openshift.io
        volumeAttributes:
          sharedConfigMap: my-share

EOF
----
