// Module included in the following assemblies:
// * openshift_images/managing_images/using-image-pull-secrets.adoc
// * post_installation_configuration/cluster-tasks.adoc
// * support/remote_health_monitoring/opting-out-of-remote-health-reporting.adoc
// * updating/updating-restricted-network-cluster/restricted-network-update-osus.adoc
// * updating/updating-restricted-network-cluster/restricted-network-update.adoc
//
// Not included, but linked to from:
// * operators/admin/olm-managing-custom-catalogs.adoc

ifeval::["{context}" == "using-image-pull-secrets"]
:image-pull-secrets:
endif::[]

:_content-type: PROCEDURE
[id="images-update-global-pull-secret_{context}"]
= 更新全局集群 pull secret

您可以通过替换当前的 pull secret 或附加新的 pull secret 来更新集群的全局 pull secret。


[重要]
====
要将集群转让给另一所有者，您必须首先在 Uccps Cluster Manager 中启动转让，然后更新集群中的 pull secret。在不启动 Uccps Cluster Manager 中的传输的情况下更新集群的 pull secret 会导致集群停止在 Uccps Cluster Manager 中报告 Telemetry 指标。

有关 传输集群所有权的更多信息，请参阅 UnionTech Uccps Cluster Manager 文档中的 "Transferring cluster ownership"。
====


.先决条件

* 您可以使用具有 `cluster-admin` 角色的用户访问集群。

.流程
. 可选： 要将新的 pull secret 附加到现有 pull secret 中，请完成以下步骤：

.. 输入以下命令下载 pull secret：
+
[source,terminal]
----
$ oc get secret/pull-secret -n openshift-config --template='{{index .data ".dockerconfigjson" | base64decode}}' ><pull_secret_location> <1>
----
<1> 提供 pull secret 文件的路径。

.. 输入以下命令来添加新 pull secret：
+
[source,terminal]
----
$ oc registry login --registry="<registry>" \ <1>
--auth-basic="<username>:<password>" \ <2>
--to=<pull_secret_location> <3>
----
<1> 提供新的 registry。您可以在同一个 registry 中包含多个软件仓库，例如： `--registry="<registry/my-namespace/my-repository>`。
<2> 提供新 registry 的凭据。
<3> 提供 pull secret 文件的路径。
+
另外，您可以对 pull secret 文件执行手动更新。

. 输入以下命令为您的集群更新全局 pull secret：
+
[source,terminal]
----
$ oc set data secret/pull-secret -n openshift-config --from-file=.dockerconfigjson=<pull_secret_location> <1>
----
<1> 提供新 pull secret 文件的路径。
+
该更新将推广至所有节点，可能需要一些时间，具体取决于集群大小。
+
[注意]
====
从 统信容器云管理平台 4.7.4 开始，对全局 pull secret 的更改不再触发节点排空或重启。
====
//Also referred to as the cluster-wide pull secret.


ifeval::["{context}" == "using-image-pull-secrets"]
:!image-pull-secrets:
endif::[]
