// Module included in the following assemblies:
//
// * post_installation_configuration/network-configuration.adoc

:_content-type: PROCEDURE
[id="installation-osp-kuryr-settings-active_{context}"]
= 在 RHOSP 上的活跃部署中调整 Kuryr 端口池设置

您可以使用自定义资源 (CR) 配置 Kuryr 如何管理 UnionTech OpenStack Platform (RHOSP) Neutron 端口，以控制在部署的集群上创建 pod 的速度和效率。

.流程

. 在命令行中，打开 Cluster Network Operator (CNO) CR 进行编辑：
+
[source,terminal]
----
$ oc edit networks.operator.openshift.io cluster
----

. 编辑设置以满足您的要求。以下示例提供了以下文件：
+
[source,yaml]
----
apiVersion: operator.openshift.io/v1
kind: Network
metadata:
  name: cluster
spec:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  serviceNetwork:
  - 172.30.0.0/16
  defaultNetwork:
    type: Kuryr
    kuryrConfig:
      enablePortPoolsPrepopulation: false <1>
      poolMinPorts: 1 <2>
      poolBatchPorts: 3 <3>
      poolMaxPorts: 5 <4>
----
<1> 将 `enablePortPoolsPrepopulation` 设置为 true，以便在命名空间中创建一个命名空间为 pod 使用专用网络的 pod 时创建 Kuryr 创建 Neutron 端口。此设置引发 Neutron 端口配额，但可以缩短生成容器集所需的时间。默认值为 `false`。
<2> 如果池中的可用端口数量低于 `poolMinPorts` 的值，Kuryr 会为池创建新端口。默认值为 `1`。
<3> `poolBatchPorts` 控制在可用端口数量低于 `poolMinPorts` 值时创建的新端口数量。默认值为 `3`。
<4> 如果池中的可用端口数量大于 `poolMaxPorts` 的值，Kuryr 会删除它们，直到数量与这个值匹配为止。将值设为 `0` 可禁用此上限，防止池被缩小。默认值为 `0`。

. 保存您的更改，再退出文本编辑器以提交更改。

[重要]
====
在正在运行的集群中修改这些选项会强制 kuryr-controller 和 kuryr-cni pod 重启。因此，创建新 pod 和服务会延迟。
====
