// Module included in the following assemblies:
//
// * installing/disconnected_install/installing-mirroring-installation-images.adoc
// * installing/disconnected_install/installing-mirroring-disconnected.adoc
// * openshift_images/samples-operator-alt-registry.adoc
// * scalability_and_performance/ztp_far_edge/ztp-deploying-far-edge-clusters-at-scale.adoc
// * updating/updating-restricted-network-cluster/restricted-network-update.adoc

ifeval::["{context}" == "updating-restricted-network-cluster"]
:restricted:
endif::[]

ifeval::["{context}" == "installing-mirroring-installation-images"]
:restricted:
endif::[]

ifeval::["{context}" == "installing-mirroring-disconnected"]
:restricted:
:oc-mirror:
endif::[]

:_content-type: PROCEDURE
[id="installation-adding-registry-pull-secret_{context}"]
= 配置允许对容器镜像进行镜像的凭证

创建容器镜像 registry 凭证文件，允许将统信的镜像镜像到您的镜像环境中。


.先决条件

* 配置了一个镜像（mirror） registry 在受限网络中使用。

.流程

在安装主机上完成以下步骤：


. 以 JSON 格式创建您的 pull secret 副本：
+
[source,terminal]
----
$ cat ./pull-secret | jq . > <path>/<pull_secret_file_in_json> <1>
----
<1> 指定到存储 pull secret 的文件夹的路径，以及您创建的 JSON 文件的名称。

+
该文件类似于以下示例：
+
[source,json]
----
{
  "auths": {
    "cloud.openshift.com": {
      "auth": "b3BlbnNo...",
      "email": "you@example.com"
    },
    "quay.io": {
      "auth": "b3BlbnNo...",
      "email": "you@example.com"
    },
    "registry.connect.redhat.com": {
      "auth": "NTE3Njg5Nj...",
      "email": "you@example.com"
    },
    "registry.redhat.io": {
      "auth": "NTE3Njg5Nj...",
      "email": "you@example.com"
    }
  }
}
----

. 为您的镜像 registry 生成 base64 编码的用户名和密码或令牌：
+
[source,terminal]
----
$ echo -n '<user_name>:<password>' | base64 -w0 <1>
BGVtbYk3ZHAtqXs=
----
<1> 通过 <user_name> 和 <password> 指定 registry 的用户名和密码。编辑 JSON 文件并添加描述 registry 的部分：

+
[source,json]
----
  "auths": {
    "<mirror_registry>": { <1>
      "auth": "<credentials>", <2>
      "email": "you@example.com"
  },

----
<1> 对于 `<mirror_registry>`，指定 registry 域名，以及您的镜像 registry 用来提供内容的可选端口。例如： `registry.example.com 或 registry.example.com:5000`
<2> 使用 `<credentials>` 为您的镜像 registry 指定 base64 编码的用户名和密码。
+
该文件类似于以下示例：
+
[source,json]
----
{
  "auths": {
    "registry.example.com": {
      "auth": "BGVtbYk3ZHAtqXs=",
      "email": "you@example.com"
    },
    "cloud.openshift.com": {
      "auth": "b3BlbnNo...",
      "email": "you@example.com"
    },
    "quay.io": {
      "auth": "b3BlbnNo...",
      "email": "you@example.com"
    },
    "registry.connect.redhat.com": {
      "auth": "NTE3Njg5Nj...",
      "email": "you@example.com"
    },
    "registry.redhat.io": {
      "auth": "NTE3Njg5Nj...",
      "email": "you@example.com"
    }
  }
}
----

ifeval::["{context}" == "installing-mirroring-installation-images"]
:!restricted:
endif::[]

ifeval::["{context}" == "updating-restricted-network-cluster"]
:!restricted:
endif::[]

ifeval::["{context}" == "installing-mirroring-disconnected"]
:!restricted:
:!oc-mirror:
endif::[]
