// Module included in the following assemblies:
//
// * machine_management/user_infra/adding-bare-metal-compute-user-infra.adoc
// * post_installation_configuration/node-tasks.adoc

:_content-type: PROCEDURE
[id="machine-user-infra-machines-pxe_{context}"]
= 通过 PXE 或 iPXE 启动来创建更多 Uswift 机器

您可以使用 PXE 或 iPXE 引导为裸机集群创建更多 UnionTech OS Cloud 20(USwift)计算机器。

.先决条件

* 获取集群计算机器的 Ignition 配置文件的 URL。在安装过程中将该文件上传到 HTTP 服务器。
* 获取您在集群安装过程中上传到 HTTP 服务器的 Uswift ISO 镜像、压缩的裸机 BIOS、`kernel` 和 `initramfs` 文件的 URL。
* 您可以访问在安装过程中为 统信容器云管理平台 集群创建机器时使用的 PXE 引导基础架构。机器必须在安装 Uswift 后从本地磁盘启动。
* 如果使用 UEFI，您可以访问在 统信容器云管理平台 安装过程中修改的 `grub.conf` 文件。

.流程

. 确认 Uswift 镜像的 PXE 或 iPXE 安装正确。

** 对于 PXE：
+
----
DEFAULT pxeboot
TIMEOUT 20
PROMPT 0
LABEL pxeboot
    KERNEL http://<HTTP_server>/rhcos-<version>-live-kernel-<architecture> <1>
    APPEND initrd=http://<HTTP_server>/rhcos-<version>-live-initramfs.<architecture>.img coreos.inst.install_dev=/dev/sda coreos.inst.ignition_url=http://<HTTP_server>/worker.ign coreos.live.rootfs_url=http://<HTTP_server>/rhcos-<version>-live-rootfs.<architecture>.img <2>
----
<1> 指定上传到 HTTP 服务器的 live kernel 文件位置。
<2> 指定上传到 HTTP 服务器的 Uswift 文件的位置。`initrd` 参数值是 live initramfs 文件的位置，`coreos.inst.ignition_url` 参数值是 `worker Ignition` 配置文件的位置，`coreos.live.rootfs_url` 参数值是 live rootfs 文件的位置。`coreos.inst.ignition_url` 和 `coreos.live.rootfs_url` 参数仅支持 HTTP 和 HTTPS。
+
此配置不会在图形控制台的机器上启用串行控制台访问。要配置不同的控制台，请在 APPEND 行中添加一个或多个 console= 参数。例如，添加 console=tty0 console=ttyS0 以将第一个 PC 串口设置为主控制台，并将图形控制台设置为二级控制台。如需更多信息，请参阅如何在 UnionTech Enterprise Linux 中设置串行终端和（或）控制台？

** 对于 iPXE：
+
----
kernel http://<HTTP_server>/rhcos-<version>-live-kernel-<architecture> initrd=main coreos.inst.install_dev=/dev/sda coreos.inst.ignition_url=http://<HTTP_server>/worker.ign coreos.live.rootfs_url=http://<HTTP_server>/rhcos-<version>-live-rootfs.<architecture>.img <1>
initrd --name main http://<HTTP_server>/rhcos-<version>-live-initramfs.<architecture>.img <2>
----
<1> 指定上传到 HTTP 服务器的 Uswift 文件的位置。kernel 参数值是 kernel 文件的位置，在 UEFI 系统中引导时需要 `initrd=main` 参数。 `coreos.inst.ignition_url` 参数值是 worker Ignition 配置文件的位置，`coreos.live.rootfs_url` 参数值则是 live rootfs 文件的位置。`coreos.inst.ignition_url` 和 `coreos.live.rootfs_url` 参数仅支持 HTTP 和 HTTPS。
<2> 指定上传到 HTTP 服务器的 `initramfs` 文件的位置。
+
+
此配置不会在图形控制台的机器上启用串行控制台访问。要配置不同的控制台，请在 内核参数 中添加一个或多个 console= 参数。例如，添加 `console=tty0 console=ttyS0` 以将第一个 PC 串口设置为主控制台，并将图形控制台设置为二级控制台。如需更多信息，请参阅如何在 UnionTech Enterprise Linux 中设置串行终端和（或）控制台？

. 使用 PXE 或 iPXE 基础架构为集群创建所需的计算机器。
