// Module included in the following assemblies:
//
// * machine_management/creating-infrastructure-machinesets.adoc
// * machine_management/creating_machinesets/creating-machineset-osp.adoc

ifeval::["{context}" == "creating-infrastructure-machinesets"]
:infra:
endif::[]

:_content-type: REFERENCE
[id="machineset-yaml-osp_{context}"]
=  RHOSP 上机器设置自定义资源的 YAML 示例

此 YAML 示例定义了一个在 UnionTech OpenStack Platform（RHOSP）上运行的机器集，并创建带有
ifndef::infra[`node-role.kubernetes.io/<role>: ""`.]
ifdef::infra[`node-role.kubernetes.io/infra: ""`.]
标记的节点
在本例中， `<infrastructure_id>` 是基础架构 ID 标签，该标签基于您在置备集群时设定的集群 ID，而
ifndef::infra[`<role>`]
ifdef::infra[`<infra>`]
则是要添加的节点标签。

[source,yaml]
----
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: <infrastructure_id> <1>
ifndef::infra[]
    machine.openshift.io/cluster-api-machine-role: <role> <2>
    machine.openshift.io/cluster-api-machine-type: <role> <2>
  name: <infrastructure_id>-<role> <3>
endif::infra[]
ifdef::infra[]
    machine.openshift.io/cluster-api-machine-role: <infra> <2>
    machine.openshift.io/cluster-api-machine-type: <infra> <2>
  name: <infrastructure_id>-infra <3>
endif::infra[]
  namespace: openshift-machine-api
spec:
  replicas: <number_of_replicas>
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: <infrastructure_id> <1>
ifndef::infra[]
      machine.openshift.io/cluster-api-machineset: <infrastructure_id>-<role> <3>
endif::infra[]
ifdef::infra[]
      machine.openshift.io/cluster-api-machineset: <infrastructure_id>-infra <3>
endif::infra[]
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: <infrastructure_id> <1>
ifndef::infra[]
        machine.openshift.io/cluster-api-machine-role: <role> <2>
        machine.openshift.io/cluster-api-machine-type: <role> <2>
        machine.openshift.io/cluster-api-machineset: <infrastructure_id>-<role> <3>
    spec:
endif::infra[]
ifdef::infra[]
        machine.openshift.io/cluster-api-machine-role: <infra> <2>
        machine.openshift.io/cluster-api-machine-type: <infra> <2>
        machine.openshift.io/cluster-api-machineset: <infrastructure_id>-infra <3>
    spec:
      metadata:
        creationTimestamp: null
        labels:
          node-role.kubernetes.io/infra: ""
      taints: <4>
      - key: node-role.kubernetes.io/infra
        effect: NoSchedule
endif::infra[]
      providerSpec:
        value:
          apiVersion: openstackproviderconfig.openshift.io/v1alpha1
          cloudName: openstack
          cloudsSecret:
            name: openstack-cloud-credentials
            namespace: openshift-machine-api
          flavor: <nova_flavor>
          image: <glance_image_name_or_location>
ifndef::infra[]
          serverGroupID: <optional_UUID_of_server_group> <4>
endif::infra[]
ifdef::infra[]
          serverGroupID: <optional_UUID_of_server_group> <5>
endif::infra[]
          kind: OpenstackProviderSpec
ifndef::infra[]
          networks: <5>
endif::infra[]
ifdef::infra[]
          networks: <6>
endif::infra[]
          - filter: {}
            subnets:
            - filter:
                name: <subnet_name>
                tags: openshiftClusterID=<infrastructure_id> <1>
ifndef::infra[]
          primarySubnet: <rhosp_subnet_UUID> <6>
endif::infra[]
ifdef::infra[]
          primarySubnet: <rhosp_subnet_UUID> <7>
endif::infra[]
          securityGroups:
          - filter: {}
            name: <infrastructure_id>-worker <1>
          serverMetadata:
            Name: <infrastructure_id>-worker <1>
            openshiftClusterID: <infrastructure_id> <1>
          tags:
          - openshiftClusterID=<infrastructure_id> <1>
          trunk: true
          userDataSecret:
            name: worker-user-data <2>
          availabilityZone: <optional_openstack_availability_zone>
----
<1> 指定基于置备集群时所设置的集群 ID 的基础架构 ID。如果已安装 Uccps CLI，您可以通过运行以下命令来获取基础架构 ID：
+
[source,terminal]
----
$ oc get -o jsonpath='{.status.infrastructureName}{"\n"}' infrastructure cluster
----
ifndef::infra[]
<2> 指定要添加的节点标签。
<3> 指定基础架构 ID 和节点标签。
<4> 要为 MachineSet 设置服务器组策略，请输入从创建服务器组返回的值。对于大多数部署，推荐使用 `anti-affinity` 或 `soft-anti-affinity` 策略。
<5> 部署到多个网络需要。要指定多个网络，请在网络数组中添加另一个条目。此外，您必须包含用作 primarySubnet 值的网络。
<6> 指定您要发布节点端点的 RHOSP 子网。通常，这与 install-config.yaml 文件中的 machineSubnet 值相同。
endif::infra[]
ifdef::infra[]
<2> 直径 `<infra>` 节点标签。
<3> 指定基础架构 ID 和 `<infra>` 节点标签。
<4> 指定一个污点，以防止将用户工作负载调度到 infra 节点上。
<5> 要为 MachineSet 设置服务器组策略，请输入从创建服务器组返回的值。对于大多数部署，推荐使用 `anti-affinity` 或 `soft-anti-affinity` 策略。
<6> 部署到多个网络需要。如果部署到多个网络，这个列表必须包含用作 `primarySubnet` 值的网络。
<7> 指定您要发布节点端点的 RHOSP 子网。通常，这与 `install-config.yaml` 文件中的 `machineSubnet` 值相同。
endif::infra[]

ifeval::["{context}" == "creating-infrastructure-machinesets"]
:!infra:
endif::[]
ifeval::["{context}" == "cluster-tasks"]
:!infra:
endif::[]
