// Module included in the following assemblies:
//
// * authentication/managing_cloud_provider_credentials/cco-mode-manual.adoc
// * authentication/managing_cloud_provider_credentials/cco-mode-sts.adoc
// * installing/installing_ibm_cloud_public/manually-creating-iam-ibm-cloud.adoc
// * updating/updating-cluster-within-minor.adoc
// * updating/updating-cluster-cli.adoc

:_content-type: PROCEDURE

ifeval::["{context}" == "configuring-iam-ibm-cloud"]
:ibm-cloud:
endif::[]

[id="manually-maintained-credentials-upgrade_{context}"]
= 使用手动维护的凭证升级集群

默认情况下，带有手动维护凭证的集群的 Cloud Credential Operator(CCO)U gradable 状态为 `False`。

* 对于次发行版本（例如从 1.1 升级到 1.2），这个状态会阻止升级，直到您解决了任何更新的权限并 添加了 CloudCredential 资源，以指示下一版本根据需要更新权限。此注解将 `Upgradable` 状态更改为 `True`。

* 对于 z-stream 版本（例如从 1.1.0 到 1.1.1），没有添加或更改任何权限，因此不会阻止升级。

在使用手动维护凭证升级集群前，您必须为要升级到的发行镜像创建新凭证。另外，您必须检查现有凭证所需的权限，并满足新版本中这些组件的任何新权限要求。


.流程

. 提取并检查 新版本的 `CredentialsRequest` 自定义资源。
+
详情请参阅您的云供应商的“手动创建 IAM”部分来了解如何获取和使用您的云所需的凭证。


. 更新集群中手动维护的凭证：

** 为新发行镜像添加的任何 `CredentialsRequest` 自定义资源创建新 secret。
** 如果存储在 secret 中的任何现有凭证的 `CredentialsRequest` 自定义资源更改了其权限要求，请根据需要更新权限。
. 当所有 secret 都对新发行版本正确时，表示集群已准备好升级：

.. 以具有 `cluster-admin` 角色的用户身份登录统信容器云管理平台CLI。

.. 编辑 `CloudCredential` 资源，以在 metadata 字段中添加 可升级至 注解：
+
[source,terminal]
----
$ oc edit cloudcredential cluster
----
+
.要添加的文本
+
[source,yaml]
----
...
  metadata:
    annotations:
      cloudcredential.openshift.io/upgradeable-to: <version_number>
...
----
+
其中 `<version_number>` 是您要升级到的版本，格式为 `x.y.z`。例如，`1.2.1` 代表统信容器云管理平台 `1.2.1`。
+
添加可升级状态进行更改的注解后，可能需要几分钟时间。

.验证

. 在 Web 控制台的 *管理员* 视角中，导航到 *管理员* -> *集群设置*.

. 要查看 CCO 状态详情，请点击 *Cluster Operators* 列表中的 *cloud-credential*。

.. 如果 `Conditions` 部分中的 `Upgradeable` 状态为 `False`，请验证 upgradeable-to 注解没有拼写错误。当 `Conditions` 部分中的 Upgradeable 状态为 `True` 时，您可以开始统信容器云管理平台升级。
