// Module included in the following assemblies:
//
// * scalability_and_performance/recommended-host-practices.adoc
// * post_installation_configuration/node-tasks.adoc

[id="master-node-sizing_{context}"]
=  Control plane 节点大小

control plane 节点资源要求取决于集群中的节点和对象的数量和类型。以下推荐的 control plane 节点大小是基于 control plane 密度测试或 _集群 密度_ 的结果。此测试会在指定数量的命名空间中创建以下对象：

- 1 镜像流
- 1 个构建  
- 5 个部署，带有 2 个 pod 副本，每个状态都挂载 4 个 secret、4 个配置映射和 1 downward API 卷
- 5 服务，每个服务都指向其中一个部署的 TCP/8080 和 TCP/8443 端口
- 1 指向前一项服务的路由
- 10 个包含 2048 随机字符串字符的 secret
- 10 个配置映射包含 2048 随机字符串字符


[options="header",cols="4*"]
|===
| worker 节点数量 |Cluster-density (namespaces) | CPU 内存 |内存 (GB)

| 27
| 500
| 4
| 16

| 120
| 1000
| 8
| 32

| 252
| 4000
| 16
| 64

| 501
| 4000
| 16
| 96

|===

在具有三个 master 或 control plane 节点的大型高密度集群中，当其中一个节点停止、重启或失败时，CPU 和内存用量将会激增。故障可能是因为电源、网络或底层基础架构出现意外问题，除了在关闭集群后重启集群以节约成本的情况下。其余两个 control plane 节点必须处理负载才能高度可用，从而增加资源使用量。另外，在升级过程中还会有这个预期，因为 master 被封锁、排空并按顺序重新引导，以应用操作系统更新以及 control plane Operator 更新。为了避免级联失败，请将 control plane 节点上的总 CPU 和内存资源使用量至最多 60% 的所有可用容量，以处理资源用量增加。相应地增加 control plane 节点上的 CPU 和内存，以避免因为缺少资源而造成潜在的停机。

[重要]
====
节点大小取决于集群中的节点和对象数量。它还取决于集群上是否正在主动创建这些对象。在创建对象时，control plane 在资源使用量方面与对象处于运行（`running`）阶段的时间相比更活跃。
====

Operator Lifecycle Manager（OLM）在 control plane 节点上运行，其内存占用量取决于 OLM 在集群中管理的命名空间和用户安装的 operator 的数量。Control plane 节点需要相应地调整大小，以避免 OOM 终止。以下数据基于集群最大测试的结果。

[options="header",cols="3*"]
|===
| 命名空间数量 | 处于空闲状态的 OLM 内存（GB） |安装了 5 个用户 operator 的 OLM 内存（GB）

| 500
| 0.823
| 1.7

| 1000
| 1.2
| 2.5

| 1500
| 1.7
| 3.2

| 2000
| 2
| 4.4

| 3000
| 2.7
| 5.6

| 4000
| 3.8
| 7.6

| 5000
| 4.2
| 9.02

| 6000
| 5.8
| 11.3

| 7000
| 6.6
| 12.9

| 8000
| 6.9
| 14.8

| 9000
| 8
| 17.7

| 10,000
| 9.9
| 21.6

|===


[重要]
====
如果使用安装程序置备的基础架构安装方法，则无法修改正在运行的 统信容器云管理平台 1.2 集群中的 control plane 节点大小。反之，您必须估计节点总数并在安装过程中使用推荐的 control plane 节点大小。
====

[重要]
====
建议基于在带有 UccpsSDN 作为网络插件的 统信容器云管理平台 集群上捕获的数据点。
====

[注意]
====
在 统信容器云管理平台 1.2 中，与 统信容器云管理平台 3.11 及之前的版本相比，系统现在默认保留半个 CPU 内核(500 millicore)。确定大小时应该考虑这一点。
====
