// Module included in the following assemblies:
//
// * monitoring/managing-alerts.adoc

[id="searching-alerts-silences-and-alerting-rules_{context}"]
= 搜索和过滤警报、静默和警报规则

您可以过滤 Alerting UI 中显示的警报、静默和警报规则。本节介绍每个可用的过滤选项。

[discrete]
== 了解警报过滤器

在 *管理员*  视角中，Alerting UI 中的 *Alerts*  页面针对与 统信容器云管理平台 默认项目和用户定义的项目相关的警报提供了详细信息。该页面包括每个警报的严重性、状态和来源摘要。另外还会显示警报进入其当前状态的时间。

您可以按警报状态、严重性和来源进行过滤。默认情况下，只会显示处于 *Firing* 状态的 *Platform* 警报。下面描述了每个警报过滤选项：

* *Alert State* 过滤器：
** *Firing*。 警报正在触发，因为满足警报条件，且可选的 for 持续时间已过。只要条件一直满足，警报将继续触发。
** *Pending*。 该警报处于活跃状态，但正在等待警报规则中指定的持续时间，然后再触发警报。
** *Silenced*。 现在，警报在定义的时间段内处于静默状态。静默会根据您定义的一组标签选择器临时将警报静音。对于符合所有列出的值或正则表达式的警报，不会发送通知。

* *Severity* 过滤器：
** *Critical*。 触发了警报的条件可能会产生重大影响。该警报在触发时需要立即关注，并且通常会传给个人或关键响应团队。
** *Warning*。 该警报针对可能需要注意的事件提供警告通知，以防止问题的发生。警告通常会路由到一个问题单系统进行非即时的审阅。
** *Info*.。该警报仅用于提供信息。
** *None*。 该警报没有定义的严重性。
** 您还可以针对与用户定义的项目相关的警报创建自定义严重性定义。

* *Source* 过滤器：
** *Platform*。 平台级别的警报仅与 统信容器云管理平台 默认项目相关。这些项目提供 统信容器云管理平台 核心功能。
** *User*。 用户警报与用户定义的项目相关。这些警报是用户创建的，并可自定义。用户定义的工作负载监控可在安装后启用，以便您观察自己的工作负载。

[discrete]
== 了解静默过滤器

在 *管理员* 视角中，Alerting UI 中的 *Silences* 页面针对应用到 统信容器云管理平台 默认项目和用户定义项目中的警报的静默提供了详细信息。该页面包括每个静默的状态以及静默结束时间的摘要。

您可以按静默状态进行过滤。默认情况下，仅显示 *Active* 和 *Pending* 静默。下面描述了每个静默状态过滤器选项：

* *Silence State* 过滤器：
** *Active* 静默处于活跃状态，在静默到期前，警报将静音。
** *Pending*。 静默已被调度，但还没有激活。
** *Expired*。静默已过期，如果满足警报条件，将发送通知。

[discrete]
== 了解警报规则过滤器

在 *管理员* 视角中，Alerting UI 中的 *Alerts Rules* 页面针对与 统信容器云管理平台 默认项目和用户定义的项目相关的警报规则提供了详细信息。该页面包括每个警报规则的状态、严重性和来源摘要。

可以按警报状态、严重性和来源过滤警报规则。默认情况下，只会显示 Platform 警报规则。下面描述了每个警报规则过滤选项：

* *Alert State* 过滤器：
** *Firing*。 警报正在触发，因为满足警报条件，且可选的 for 持续时间已过。只要条件一直满足，警报将继续触发。
** *Pending*。 该警报处于活跃状态，但正在等待警报规则中指定的持续时间，然后再触发警报。
** *Silenced*。 现在，警报在定义的时间段内处于静默状态。静默会根据您定义的一组标签选择器临时将警报静音。对于符合所有列出的值或正则表达式的警报，不会发送通知。
** *Not Firing*。 警报未触发。

* *Severity* 过滤器：
** *Critical*。 警报规则中定义的条件可能会产生重大影响。如果满足这些条件，需要立即关注。与该规则相关的警报通常会传给个人或关键响应团队。
** *Warning*。 警报规则中定义的条件可能需要注意，以防止问题的发生。与该规则相关的警报通常会路由到一个问题单系统进行非即时的审阅。
** *Info*。 警报规则仅提供信息警报。
** *None*。 该警报规则没有定义的严重性。
** 您还可以针对与用户定义的项目相关的警报规则创建自定义严重性定义。

* *Source* 过滤器：
** *Platform*。平台级别的警报规则仅与 统信容器云管理平台 默认项目相关。这些项目提供 统信容器云管理平台 核心功能。
** *User*。 用户定义的工作负载警报规则与用户定义的项目相关。这些警报规则是用户创建的，并可自定义。用户定义的工作负载监控可在安装后启用，以便您观察自己的工作负载。

[discrete]
== 在 开发者 视角中搜索和过滤警报、静默和警报规则

在 *开发者* 视角中，Alerting UI 中的 Alerts 页面提供了与所选项目相关的警报和静默的组合视图。对于每个显示的警报，都提供了相关警报规则的链接。

在该视图中，您可以按警报状态和严重性进行过滤。默认情况下，如果您有访问所选项目的权限，则会显示项目中的所有警报。这些过滤器与针对 *管理员* 视角描述的过滤器相同。
