// Module included in the following assemblies:
//
// * nodes/nodes-scheduler-node-affinity.adoc

:_content-type: CONCEPT
[id="nodes-scheduler-node-affinity-about_{context}"]
= 了解节点关联性

节点关联性允许 pod 指定与可以放置该 pod 的一组节点的关联性。节点对放置没有控制权。

例如，您可以将 pod 配置为仅在具有特定 CPU 或位于特定可用区的节点上运行。

节点关联性规则有两种，即必要规则和偏好规则。

必须满足必要规则，pod 才能调度到节点上。偏好规则指定在满足规则时调度程序会尝试强制执行规则，但不保证一定能强制执行成功。

[注意]
====
如果节点标签在运行时改变，使得不再满足 pod 上的节点关联性规则，该 pod 将继续在这个节点上运行。
====

您可以通过 Pod 规格文件配置节点关联性。您可以指定必要规则或偏好规则，或同时指定这两种规则。如果您同时指定，节点必须首先满足必要规则，然后尝试满足偏好规则。

下例中的 Pod spec 包含一条规则，要求 pod 放置到具有键为  `e2e-az-NorthSouth` 且值为 `e2e-az-North`  或 `e2e-az-South` 的标签的节点上：

.具有节点关联性必要规则的 pod 配置文件示例
[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity: <1>
      requiredDuringSchedulingIgnoredDuringExecution: <2>
        nodeSelectorTerms:
        - matchExpressions:
          - key: e2e-az-NorthSouth <3>
            operator: In <4>
            values:
            - e2e-az-North <3>
            - e2e-az-South <3>
  containers:
  - name: with-node-affinity
    image: docker.io/ocpqe/hello-pod
----

<1> 用于配置节点关联性的小节。
<2> 定义必要规则。
<3> 必须匹配键/值对（标签）才会应用该规则。
<4> 运算符表示节点上的标签和 Pod 规格中 `matchExpression` 参数的值集合之间的关系。这个值可以是 `In`, `NotIn`, `Exists`, 或 `DoesNotExist`, `Lt`, 或 `Gt`.

例中的节点规格包含一条偏好规则，其规定优先为 pod 选择具有键为  `e2e-az-EastWest` 且值为 `e2e-az-East` 或 `e2e-az-West` 的节点：

.具有节点关联性偏好规则的 pod 配置文件示例
[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity: <1>
      preferredDuringSchedulingIgnoredDuringExecution: <2>
      - weight: 1 <3>
        preference:
          matchExpressions:
          - key: e2e-az-EastWest <4>
            operator: In <5>
            values:
            - e2e-az-East <4>
            - e2e-az-West <4>
  containers:
  - name: with-node-affinity
    image: docker.io/ocpqe/hello-pod
----

<1> 用于配置节点关联性的小节。
<2> 定义偏好规则。
<3> 为偏好规则指定权重。优先选择权重最高的节点。
<4> 必须匹配键/值对（标签）才会应用该规则。
<5> 运算符表示节点上的标签和 Pod 规格中 `matchExpression` 参数的值集合之间的关系。这个值可以是 `In`, `NotIn`, `Exists`, 或 `DoesNotExist`, `Lt`, 或 `Gt`.

没有明确的节点反关联性概念，但使用 NotIn 或 DoesNotExist 运算符就能实现这种行为。

[注意]
====
如果您在同一 pod 配置中同时使用节点关联性和节点选择器，请注意以下几点：

* 如果同时配置了 `nodeSelector` 和 `nodeAffinity`，则必须满足这两个条件时 pod 才能调度到候选节点。

* 如果您指定了多个与 `nodeAffinity`  类型关联的  `nodeSelectorTerms`  `nodeSelectorTerms` 那么其中一个 nodeSelectorTerms 满足时 pod 就能调度到节点上。

* 如果您指定了多个与 `nodeSelectorTerms`  关联的 `matchExpressions` 那么只有所有 `matchExpressions` 都满足时 pod 才能调度到节点上。
====

