// Module included in the following assemblies:
//
// * nodes/clusters/nodes-cluster-overcommit.adoc

:_content-type: PROCEDURE
[id="nodes-cluster-resource-override-deploy-console_{context}"]
= 使用 Web 控制台安装 Cluster Resource Override Operator

您可以使用 统信容器云管理平台 Web 控制台来安装 Cluster Resource Override Operator，以帮助控制集群中的过量使用。

.先决条件

* 如果容器上未设置限值，Cluster Resourceoverride Operator 将没有作用。您必须使用一个 `LimitRange` 对象为项目指定默认限值，或在 Pod spec 中配置要应用的覆盖的限制。

.流程

使用 统信容器云管理平台 web 控制台安装 Cluster Resource Override Operator：

. 在 统信容器云管理平台 web 控制台中进入  *Home* -> *Projects*

.. 点 *Create Project*.

.. 指定 `clusterresourceoverride-operator` 作为项目的名称。

.. 点击 *Create*.

. 进入 *Operators* -> *OperatorHub*.

.. 从可用 Operator 列表中选择 *ClusterResourceOverride Operator* ，再点击 *Install*.

.. 在 *Install Operator* 页面中，确保为 *Installation Mode* 选择了 *A specific Namespace on the cluster* 

.. 确保为 *Installed Namespace* 选择了 *clusterresourceoverride-operator* 。

.. 指定 *Update Channel* 和 *Approval Strategy*.

.. 点击 *Install*.

. 在 *Installed Operators* 页面中，点 *ClusterResourceOverride*.

.. 在 *ClusterResourceOverride Operator* 详情页面中，点 *Create Instance*.

.. 在 *Create ClusterResourceOverride* 页面 中，编辑 YAML 模板以根据需要设置过量使用值：
+
[source,yaml]
----
apiVersion: operator.autoscaling.openshift.io/v1
kind: ClusterResourceOverride
metadata:
  name: cluster <1>
spec:
  podResourceOverride:
    spec:
      memoryRequestToLimitPercent: 50 <2>
      cpuRequestToLimitPercent: 25 <3>
      limitCPUToMemoryPercent: 200 <4>
----
<1> 名称必须是 `cluster`。
<2> 可选。指定在 1-100 之间覆盖容器内存限值的百分比（如果使用的话）。默认值为 50.
<3> 可选。指定在 1-100 之间覆盖容器 CPU 限值的百分比（如果使用的话）。默认值为 25。
<4> 可选。如果使用，请指定覆盖容器内存限值的百分比。以 100% 扩展 1Gi RAM， 等于 1 个 CPU 内核。这会在覆盖 CPU 请求前进行处理（如果已配置）。默认值为 200。

.. 点击 *Create*.

. 通过检查集群自定义资源的状态来检查准入 Webhook 的当前状态：

.. 在 *ClusterResourceOverride Operator* 页面，点击 *cluster*.

.. 在 *ClusterResourceOverride Details* 页中，点击 *YAML*. 当 webhook 被调用时， `mutatingWebhookConfigurationRef` 项会出现。
+
[source,yaml]
----
apiVersion: operator.autoscaling.openshift.io/v1
kind: ClusterResourceOverride
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"operator.autoscaling.openshift.io/v1","kind":"ClusterResourceOverride","metadata":{"annotations":{},"name":"cluster"},"spec":{"podResourceOverride":{"spec":{"cpuRequestToLimitPercent":25,"limitCPUToMemoryPercent":200,"memoryRequestToLimitPercent":50}}}}
  creationTimestamp: "2019-12-18T22:35:02Z"
  generation: 1
  name: cluster
  resourceVersion: "127622"
  selfLink: /apis/operator.autoscaling.openshift.io/v1/clusterresourceoverrides/cluster
  uid: 978fc959-1717-4bd1-97d0-ae00ee111e8d
spec:
  podResourceOverride:
    spec:
      cpuRequestToLimitPercent: 25
      limitCPUToMemoryPercent: 200
      memoryRequestToLimitPercent: 50
status:

....

    mutatingWebhookConfigurationRef: <1>
      apiVersion: admissionregistration.k8s.io/v1beta1
      kind: MutatingWebhookConfiguration
      name: clusterresourceoverrides.admission.autoscaling.openshift.io
      resourceVersion: "127621"
      uid: 98b3b8ae-d5ce-462b-8ab5-a729ea8f38f3

....

----
<1> 引用 `ClusterResourceOverride` 准入Webhook。

////
. When the webhook is called, you can add a label to any Namespaces where you want overrides enabled:

.. Click `Administration` -> `Namespaces`.

.. Click the Namespace to edit then click *YAML*.

.. Add the label under `metadata`:
+
----
apiVersion: v1
kind: Namespace
metadata:

....

  labels:
    clusterresourceoverrides.admission.autoscaling.openshift.io: enabled <1>
---- 
<1> Add the `clusterresourceoverrides.admission.autoscaling.openshift.io: enabled` label to the Namespace.
////
