// Module included in the following assemblies:
//
// * nodes/nodes-pods-secrets.adoc

:_content-type: CONCEPT
[id="nodes-pods-secrets-creating_{context}"]
= 了解如何创建 secret

作为管理员，您必须先创建 secret，然后开发人员才能创建依赖于该 secret 的 pod。

在创建 secret 时：

. 创建包含您要保留 secret 的数据的 secret 对象。在以下部分中取消每个 secret 类型所需的特定数据。
+
.创建不透明 secret 的 YAML 对象示例

[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
type: Opaque <1>
data: <2>
  username: dmFsdWUtMQ0K
  password: dmFsdWUtMQ0KDQo=
stringData: <3>
  hostname: myapp.mydomain.com
  secret.properties: |
    property1=valueA
    property2=valueB
----
<1> 指定 secret 的类型。
<2> 指定编码的字符串和数据。
<3> 指定解码的字符串和数据。
+
使用 `data` 或 `stringdata` 字段，不能同时使用这两个字段。

. 更新 pod 的服务帐户以引用 secret：
+
.使用 secret 的服务帐户的 YAML
+
[source,yaml]
----
apiVersion: v1
kind: ServiceAccount
 ...
secrets:
- name: test-secret
----

. 创建以环境变量或文件（使用 secret 卷）形式消耗 secret 的 pod：
+
.pod 的 YAML 使用 secret 数据填充卷中的文件
+
[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: secret-example-pod
spec:
  containers:
    - name: secret-test-container
      image: busybox
      command: [ "/bin/sh", "-c", "cat /etc/secret-volume/*" ]
      volumeMounts: <1>
          - name: secret-volume
            mountPath: /etc/secret-volume <2>
            readOnly: true <3>
  volumes:
    - name: secret-volume
      secret:
        secretName: test-secret <4>
  restartPolicy: Never
----
<1> 为每个需要 secret 的容器添加 `volumeMounts` 字段。
<2> 指定您希望显示 secret 的未使用目录名称。secret 数据映射中的每个密钥都将成为 `mountPath` 下的文件名。
<3> 设置为 `true` 。如果为 true，这指示驱动程序提供只读卷。
<4> 指定 secret 的名称。
+
.pod 的 YAML 使用 secret 数据填充环境变量
+
[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: secret-example-pod
spec:
  containers:
    - name: secret-test-container
      image: busybox
      command: [ "/bin/sh", "-c", "export" ]
      env:
        - name: TEST_SECRET_USERNAME_ENV_VAR
          valueFrom:
            secretKeyRef: <1>
              name: test-secret
              key: username
  restartPolicy: Never
----
<1> 指定消耗 secret 密钥的环境变量。
+
.构建配置的 YAML 使用 secret 数据填充环境变量
+
[source,yaml]
----
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: secret-example-bc
spec:
  strategy:
    sourceStrategy:
      env:
      - name: TEST_SECRET_USERNAME_ENV_VAR
        valueFrom:
          secretKeyRef: <1>
            name: test-secret
            key: username
----
<1> 指定消耗 secret 密钥的环境变量。

== Secret 创建限制

若要使用 secret，pod 需要引用该 secret。可以通过三种方式将 secret 用于 Pod：

- 为容器产生环境变量。
- 作为挂载到一个或多个容器上的卷中的文件。
- 在拉取 Pod 的镜像时通过 kubelet 使用。

卷类型 secret 使用卷机制将数据作为文件写入到容器中。镜像拉取 secret 使用服务帐户，将 secret 自动注入到命名空间中的所有 pod。

当模板包含 secret 定义时，模板使用提供的 secret 的唯一方法是确保验证 secret 卷源通过验证，并且指定的对象引用实际指向 Secret 类型的对象。因此，secret 需要在依赖它的任何 Pod 之前创建。确保这一点的最有效方法是通过使用服务帐户自动注入。

Secret API 对象驻留在命名空间中。它们只能由同一命名空间中的 pod 引用。

每个 secret 的大小限制为 1MB。这是为了防止创建可能会耗尽 apiserver 和 kubelet 内存的大型 secret。不过，创建许多较小的 secret 也可能会耗尽内存。
