// Module included in the following assemblies:
//
// nodes/clusters/nodes-cluster-enabling-features.adoc

:_content-type: CONCEPT
[id="nodes-cluster-enabling-features-about_{context}"]
= 了解功能门

您可以使用 `FeatureGate` 自定义资源（CR）在集群中启用特定的功能集。功能集是 统信容器云管理平台 功能的集合，默认情况下不启用。

您可以使用 `FeatureGate` CR 激活以下功能集：

* `TechPreviewNoUpgrade`. 这个功能集是当前技术预览功能的子集。此功能集允许您在测试集群中启用这些技术预览功能，您可以在测试集群中完全测试它们，同时保留生产集群中禁用的功能。启用此功能集无法撤消并阻止次版本更新。不建议在生产环境集群中使用此功能集。
+
此功能集启用了以下技术预览功能：
+
** Microsoft Azure File CSI Driver Operator。 使用 Microsoft Azure File Storage 的 Container Storage Interface(CSI)驱动程序启用持久性卷(PV)置备。
** CSI 自动迁移。为支持的树内卷插件启用自动迁移，并将其对应的 Container Storage Interface(CSI)驱动程序。支持：
*** Amazon Web Services (AWS) Elastic Block Storage (EBS)
*** OpenStack Cinder
*** Azure Disk
*** Azure File
*** Google Cloud Platform Persistent Disk (CSI)
*** VMware vSphere
** Cluster Cloud Controller Manager Operator启用 Cluster Cloud Controller Manager Operator 而不是树内云控制器。作为技术预览提供：
*** Alibaba Cloud
*** Amazon Web Services (AWS)
*** Google Cloud Platform (GCP)
*** IBM Cloud
*** Microsoft Azure
*** {rh-openstack-first}
*** VMware vSphere
** 共享资源 CSI 驱动程序
** 统信容器云管理平台 构建系统的 CSI 卷支持
** 节点上的交换内存

////
Do not document per Derek Carr: https://github.com/openshift/api/pull/370#issuecomment-510632939
|`CustomNoUpgrade` ^[2]^
|Allows the enabling or disabling of any feature. Turning on this feature set on is not supported, cannot be undone, and prevents upgrades.

[.small]
--
1.
2. If you use the `CustomNoUpgrade` feature set to disable a feature that appears in the web console, you might see that feature, but
no objects are listed. For example, if you disable builds, you can see the *Builds* tab in the web console, but there are no builds present. If you attempt to use commands associated with a disabled feature, such as `oc start-build`, {product-title} displays an error.

[NOTE]
====
If you disable a feature that any application in the cluster relies on, the application might not
function properly, depending upon the feature disabled and how the application uses that feature.
====
////
