// Module included in the following assemblies:
//
// * nodes/nodes-cluster-resource-configure.adoc

:_content-type: CONCEPT
[id="nodes-cluster-resource-configure-about_{context}"]
= 了解管理应用程序内存

在继续操作前，建议您仔细阅读 统信容器云管理平台 如何管理计算资源的概述。

对于每种资源（内存、CPU 或存储），统信容器云管理平台 允许在 pod 中的各个容器上设置可选的 *request* 和 *limit* 值。

注意以下关于内存请求和内存限制的信息：

* *内存请求*

  - 如果指定，内存请求值会影响 统信容器云管理平台 调度程序。将容器调度到节点时，调度程序会考虑内存请求，然后在所选节点上隔离出请求的内存供该容器使用。

  - 如果节点的内存已用尽，统信容器云管理平台 将优先驱除其内存用量超出内存请求最多的容器。在严重的内存耗尽情形中，节点 OOM 终止程序可以根据类似的指标选择并终止容器中的一个进程。

  - 集群管理员可以分配配额，或者分配内存请求值的默认值。

  - 集群管理员可以覆盖开发人员指定的内存请求值，以便管理集群过量使用。

* *内存限制*

  - 如果指定，内存限制值针对可在容器中所有进程间分配的内存提供硬性限制。

  - 如果分配给容器中所有进程的内存超过内存限制，则节点超出内存（OOM）终止程序将立即选择并终止容器中的一个进程。

  - 如果同时指定了内存请求和限制，则内存限制必须大于或等于内存请求量。

  - 集群管理员可以分配配额，或者分配内存限制值的默认值。

  - 最小内存限值为 12MB。如果容器因为一个 Cannot allocate memory pod 事件启动失败，这代表内存限制太低。增加或删除内存限制。删除限制可让 pod 消耗无限的节点资源。
 
[id="nodes-cluster-resource-configure-about-memory_{context}"]
== 管理应用程序内存策略

如下是 统信容器云管理平台 上调整应用程序内存大小的步骤：

. *确定预期的容器内存用量*
+
从经验判断（例如，通过独立的负载测试），根据需要确定容器内存用量的预期平均值和峰值。需要考虑容器中有可能并行运行的所有进程：例如，主应用程序是否生成任何辅助脚本？

. *确定风险嗜好*
+
确定用于驱除的风险嗜好。如果风险嗜好较低，则容器应根据预期的峰值用量加上一个安全裕度百分比来请求内存。如果风险嗜好较高，那么根据预期的平均用量请求内存可能更为妥当。

. *设定容器内存请求*
+
根据以上所述设定容器内存请求。请求越能准确表示应用程序内存用量越好。如果请求过高，集群和配额用量效率低下。如果请求过低，应用程序驱除的几率就会提高。

. *根据需要设定容器内存限制*
+
在必要时，设定容器内存限制。如果容器中所有进程的总内存用量超过限制，那么设置限制会立即终止容器进程，所以这既有利也有弊。一方面，可能会导致过早出现意料之外的过量内存使用（“快速失败”）；另一方面，也会突然终止进程。
+
需要注意的是，有些 统信容器云管理平台 集群可能要求设置限制；有些集群可能会根据限制覆盖请求；而且有些应用程序镜像会依赖于设置的限制，因为这比请求值更容易检测。
+
如果设置内存限制，其大小不应小于预期峰值容器内存用量加上安全裕度百分比。

. *确保应用程序经过性能优化*
+
在适当时，确保应用程序已根据配置的请求和限制进行了性能优化。对于池化内存的应用程序（如 JVM），这一步尤为相关。本页的其余部分将介绍这方面的内容。
