// Module included in the following assemblies:
//
// * nodes/nodes-pods-secrets.adoc

:_content-type: CONCEPT
[id="nodes-pods-secrets-about_{context}"]
= 了解 secrets

`Secret` 对象类型提供了一种机制来保存敏感信息，如密码、统信容器云管理平台 客户端配置文件和私有源存储库凭证等。secret 将敏感内容与 Pod 分离。您可以使用卷插件将 secret 信息挂载到容器中，系统也可以使用 secret 代表 Pod 执行操作。

主要属性包括：

- Secret 数据可以独立于其定义来引用。
- Secret 数据卷由临时文件工具 (tmpfs) 支持，永远不会停留在节点上。
- Secret 数据可以在命名空间内共享。

.YAML Secret 对象定义

[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
  namespace: my-namespace
type: Opaque <1>
data: <2>
  username: dmFsdWUtMQ0K <3>
  password: dmFsdWUtMg0KDQo=
stringData: <4>
  hostname: myapp.mydomain.com <5>
----
<1> 指示 secret 的键和值的结构。
<2> data 字段中允许的键格式必须符合 Kubernetes 标识符术语表中 *DNS_SUBDOMAIN* 值的规范。
<3> 与 data 映射中键关联的值必须采用 base64 编码。
<4> stringData 映射中的条目将转换为 base64，然后该条目将自动移动到 data 映射中。此字段是只写的；其值仅通过 data 字段返回。
<5> 与 stringData 映射中键关联的值由纯文本字符串组成。

您必须先创建 secret，然后创建依赖于此 secret 的 Pod。

在创建 secret 时：

- 使用 secret 数据创建 secret 对象。
- 更新 pod 的服务帐户以允许引用该 secret。
- 创建以环境变量或文件（使用 secret 卷）形式消耗 secret 的 pod。

[id="nodes-pods-secrets-about-types_{context}"]
== secrets 类型

type 字段中的值指明 secret 的键名称和值的结构。此类型可用于强制使 secret 对象中存在用户名和密钥。如果您不想进行验证，请使用 opaque 类型，这也是默认类型。

指定以下一种类型来触发最小服务器端验证，确保 secret 数据中存在特定的键名称：

* `kubernetes.io/service-account-token`。使用服务帐户令牌。
* `kubernetes.io/basic-auth`。搭配基本身份验证使用。
* `kubernetes.io/ssh-auth`。搭配 SSH 密钥身份验证使用。
* `kubernetes.io/tls`。搭配 TLS 证书颁发机构使用。

如果您不想要验证，请指定 type: Opaque，即 secret 没有声明键名称或值需要符合任何约定。opaque secret 允许使用无结构 key:value 对，可以包含任意值。

[注意]
====
您可以指定其他任意类型，如 `example.com/my-secret-type`。这些类型不是在服务器端强制执行，而是表明 secret 的创建者意在符合该类型的键/值要求。
====

如需不同 secret 类型的示例，请参阅使用 secret 中的代码示例。

[id="nodes-pods-secrets-about-keys_{context}"]
== Secret 数据密钥

Secret 密钥必须在 DNS 子域中。
