// Module included in the following assemblies:
//
// * nodes/nodes-nodes-managing.adoc
// * post_installation_configuration/machine-configuration-tasks.adoc

:_content-type: PROCEDURE
[id="nodes-nodes-kernel-arguments_{context}"]
= 为节点添加内核参数

在一些特殊情况下，您可能需要为集群中的一组节点添加内核参数。进行此操作时应小心谨慎，而且您必须先清楚了解所设参数的影响。

[警告]
====
不当使用内核参数会导致系统变得无法引导。
====

您可以设置的内核参数示例包括：

* **enforcing=0**: 将 Security Enhanced Linux（SELinux）配置为以 permissive 模式运行。在 permissive 模式中，系统会象 SELinux 一样加载安全策略，包括标记对象并在日志中记录访问拒绝条目，但它并不会拒绝任何操作。虽然不建议在生产环境系统中使用 permissive 模式，但 permissive 模式会有助于调试。

* **nosmt**: 在内核中禁用对称多线程 (SMT)。多线程允许每个 CPU 有多个逻辑线程。您可以在多租户环境中考虑使用 nosmt，以减少潜在的跨线程攻击风险。禁用 SMT 在本质上相当于选择安全性而非性能。

ifndef::openshift-origin[]
* **systemd.unified_cgroup_hierarchy**: 启用 Linux 控制组版本 2 (cgroups v2)。cgroup v2 是内核的 control groups 的下一个版本，它带有多个改进。
+
[重要]
====
Uccps cgroups版本2特性在开发者预览中，目前红帽不支持。
====
endif::openshift-origin[]


如需内核参数的列表和描述，请参阅 Kernel.org 内核参数。

在以下流程中，您要创建一个用于标识以下内容的 MachineConfig 对象：

* 您要添加内核参数的一组机器。本例中为具有 worker 角色的机器。
* 附加到现有内核参数末尾的内核参数。
* 指示机器配置列表中应用更改的位置的标签。

.先决条件
* 具有正常运行的 统信容器云管理平台 集群的管理特权。

.流程

. 列出 统信容器云管理平台 集群的现有 `MachineConfig` 对象，以确定如何标记您的机器配置：
+
[source,terminal]
----
$ oc get MachineConfig
----
+
.输出示例
[source,terminal]
----
NAME                                               GENERATEDBYCONTROLLER                      IGNITIONVERSION   AGE
00-master                                          52dd3ba6a9a527fc3ab42afac8d12b693534c8c9   3.2.0             33m
00-worker                                          52dd3ba6a9a527fc3ab42afac8d12b693534c8c9   3.2.0             33m
01-master-container-runtime                        52dd3ba6a9a527fc3ab42afac8d12b693534c8c9   3.2.0             33m
01-master-kubelet                                  52dd3ba6a9a527fc3ab42afac8d12b693534c8c9   3.2.0             33m
01-worker-container-runtime                        52dd3ba6a9a527fc3ab42afac8d12b693534c8c9   3.2.0             33m
01-worker-kubelet                                  52dd3ba6a9a527fc3ab42afac8d12b693534c8c9   3.2.0             33m
99-master-generated-registries                     52dd3ba6a9a527fc3ab42afac8d12b693534c8c9   3.2.0             33m
99-master-ssh                                                                                 3.2.0             40m
99-worker-generated-registries                     52dd3ba6a9a527fc3ab42afac8d12b693534c8c9   3.2.0             33m
99-worker-ssh                                                                                 3.2.0             40m
rendered-master-23e785de7587df95a4b517e0647e5ab7   52dd3ba6a9a527fc3ab42afac8d12b693534c8c9   3.2.0             33m
rendered-worker-5d596d9293ca3ea80c896a1191735bb1   52dd3ba6a9a527fc3ab42afac8d12b693534c8c9   3.2.0             33m
----

. 创建一个用于标识内核参数的 `MachineConfig` 对象文件 (例如 `05-worker-kernelarg-selinuxpermissive.yaml`)
+
[source,yaml]
----
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker<1>
  name: 05-worker-kernelarg-selinuxpermissive<2>
spec:
  config:
    ignition:
      version: 3.2.0
  kernelArguments:
    - enforcing=0<3>
----
+
<1> 仅将新内核参数应用到 worker 节点。
<2> 用于标识它插入到机器配置中的什么位置（05）以及发挥什么作用（添加一个内核参数来配置 SELinux permissive 模式）。
<3> 将确切的内核参数标识为 `enforcing=0`.
. 创建新机器配置：
+
. 检查机器配置以查看是否添加了新配置：
+
[source,terminal]
----
$ oc get MachineConfig
----
+
.输出示例
[source,terminal]
----
NAME                                               GENERATEDBYCONTROLLER                      IGNITIONVERSION   AGE
00-master                                          52dd3ba6a9a527fc3ab42afac8d12b693534c8c9   3.2.0             33m
00-worker                                          52dd3ba6a9a527fc3ab42afac8d12b693534c8c9   3.2.0             33m
01-master-container-runtime                        52dd3ba6a9a527fc3ab42afac8d12b693534c8c9   3.2.0             33m
01-master-kubelet                                  52dd3ba6a9a527fc3ab42afac8d12b693534c8c9   3.2.0             33m
01-worker-container-runtime                        52dd3ba6a9a527fc3ab42afac8d12b693534c8c9   3.2.0             33m
01-worker-kubelet                                  52dd3ba6a9a527fc3ab42afac8d12b693534c8c9   3.2.0             33m
05-worker-kernelarg-selinuxpermissive                                                         3.2.0             105s
99-master-generated-registries                     52dd3ba6a9a527fc3ab42afac8d12b693534c8c9   3.2.0             33m
99-master-ssh                                                                                 3.2.0             40m
99-worker-generated-registries                     52dd3ba6a9a527fc3ab42afac8d12b693534c8c9   3.2.0             33m
99-worker-ssh                                                                                 3.2.0             40m
rendered-master-23e785de7587df95a4b517e0647e5ab7   52dd3ba6a9a527fc3ab42afac8d12b693534c8c9   3.2.0             33m
rendered-worker-5d596d9293ca3ea80c896a1191735bb1   52dd3ba6a9a527fc3ab42afac8d12b693534c8c9   3.2.0             33m
----

. 检查节点：
+
[source,terminal]
----
$ oc get nodes
----
+
.输出示例
[source,terminal]
----
NAME                           STATUS                     ROLES    AGE   VERSION
ip-10-0-136-161.ec2.internal   Ready                      worker   28m   v1.23.0
ip-10-0-136-243.ec2.internal   Ready                      master   34m   v1.23.0
ip-10-0-141-105.ec2.internal   Ready,SchedulingDisabled   worker   28m   v1.23.0
ip-10-0-142-249.ec2.internal   Ready                      master   34m   v1.23.0
ip-10-0-153-11.ec2.internal    Ready                      worker   28m   v1.23.0
ip-10-0-153-150.ec2.internal   Ready                      master   34m   v1.23.0
----
+
您可以发现，在应用更改时每个 worker 节点上的调度都会被禁用。

. 前往其中一个 worker 节点并列出内核命令行参数（主机上的 /proc/cmdline 中），以检查内核参数确实已发挥作用：
+
[source,terminal]
----
$ oc debug node/ip-10-0-141-105.ec2.internal
----
+
.输出示例
[source,terminal]
----
Starting pod/ip-10-0-141-105ec2internal-debug ...
To use host binaries, run `chroot /host`

sh-4.2# cat /host/proc/cmdline
BOOT_IMAGE=/ostree/rhcos-... console=tty0 console=ttyS0,115200n8
rootflags=defaults,prjquota rw root=UUID=fd0... ostree=/ostree/boot.0/rhcos/16...
coreos.oem.id=qemu coreos.oem.id=ec2 ignition.platform.id=ec2 enforcing=0

sh-4.2# exit
----
+
您应看到 `enforcing=0` 参数已添加至其他内核参数。
