// Module included in the following assemblies:
//
// * nodes/nodes-scheduler-node-selector.adoc

:_content-type: PROCEDURE
[id="nodes-scheduler-node-selectors-cluster_{context}"]
= 创建默认的集群范围节点选择器

您可以组合使用 pod 上的默认集群范围节点选择器和节点上的标签，将集群中创建的所有 pod 限制到特定节点。

使用集群范围节点选择器时，如果您在集群中创建 pod,统信容器云管理平台 会将默认节点选择器添加到 pod，并将该 pod 调度到具有匹配标签的节点。

您可以通过编辑调度程序 Operator 自定义资源（CR）来配置集群范围节点选择器。您可为节点、机器集或机器配置添加标签。将标签添加到机器集可确保节点或机器停机时，新节点具有标签。如果节点或机器停机，添加到节点或机器配置的标签不会保留。

[注意]
====
您可以向 pod 添加额外的键/值对。但是，您无法为一个默认的键添加不同的值。
====

.流程

添加默认的集群范围节点选择器：

. 编辑调度程序 Operator CR 以添加默认的集群范围节点选择器：
+
[source,terminal]
----
$ oc edit scheduler cluster
----
+
.使用节点选择器的调度程序 Operator CR 示例
[source,yaml]
----
apiVersion: config.openshift.io/v1
kind: Scheduler
metadata:
  name: cluster
...
spec:
  defaultNodeSelector: type=user-node,region=east <1>
  mastersSchedulable: false
----
<1> 使用适当的 `<key>:<value>` 对添加节点选择器。

完成此更改后，请等待重新部署 `openshift-kube-apiserver` 项目中的 pod。这可能需要几分钟。只有重新部署 pod 后，默认的集群范围节点选择器才会生效。

. 通过使用机器集或直接编辑节点，为节点添加标签：

* 在创建节点时，使用机器集向由机器集管理的节点添加标签：

.. 运行以下命令，将标签添加到 `MachineSet` 对象中：
[source,terminal]
----
$ oc patch MachineSet <name> --type='json' -p='[{"op":"add","path":"/spec/template/spec/metadata/labels",
 "value":{"<key>"="<value>","<key>"="<value>"}}]'  -n openshift-machine-api <1>
----
<1> 为每个标识添加 `<key>/<value>` 对。
+
例如：
+
[source,terminal]
----
$ oc patch MachineSet ci-ln-l8nry52-f76d1-hl7m7-worker-c --type='json' 
-p='[{"op":"add","path":"/spec/template/spec/metadata/labels", "value":{"type":"user-node","region":"east"}}]' 
 -n openshift-machine-api
----
+
[提示]
====
您还可以应用以下 YAML 来向机器集中添加标签：

[source,yaml]
----
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: <machineset>
  namespace: openshift-machine-api
spec:
  template:
    spec:
      metadata:
        labels:
          region: "east"
          type: "user-node"
----
====

.. 使用 oc edit 命令验证标签是否已添加到 `MachineSet` 对象中：
+
例如：
+
[source,terminal]
----
$ oc edit MachineSet abc612-msrtw-worker-us-east-1c -n openshift-machine-api
----
+
.`MachineSet` 对象示例
[source,yaml]
----
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
  ...
spec:
  ...
  template:
    metadata:
  ...
    spec:
      metadata:
        labels:
          region: east
          type: user-node
  ...
----

.. 通过缩减至 0 并扩展节点来重新部署与该机器集关联的节点：
+
例如：
+
[source,terminal]
----
$ oc scale --replicas=0 MachineSet ci-ln-l8nry52-f76d1-hl7m7-worker-c -n openshift-machine-api
----
+
[source,terminal]
----
$ oc scale --replicas=1 MachineSet ci-ln-l8nry52-f76d1-hl7m7-worker-c -n openshift-machine-api
----

.. 当节点就绪并可用时，使用 oc get 命令验证该标签是否已添加到节点：
+
[source,terminal]
----
$ oc get nodes -l <key>=<value>
----
+
例如：
+
[source,terminal]
----
$ oc get nodes -l type=user-node
----
+
.输出示例
[source,terminal]
----
NAME                                       STATUS   ROLES    AGE   VERSION
ci-ln-l8nry52-f76d1-hl7m7-worker-c-vmqzp   Ready    worker   61s   v1.23.0
----

* 直接向节点添加标签：

.. 为节点编辑 Node 对象：
+
[source,terminal]
----
$ oc label nodes <name> <key>=<value>
----
+
例如，若要为以下节点添加标签：
+
[source,terminal]
----
$ oc label nodes ci-ln-l8nry52-f76d1-hl7m7-worker-b-tgq49 type=user-node region=east
----
+
[提示]
====
您还可以应用以下 YAML 来向节点添加标签：

[source,yaml]
----
kind: Node
apiVersion: v1
metadata:
  name: <node_name>
  labels:
    type: "user-node"
    region: "east"
----
====

.. 使用 oc get 命令验证标签是否已添加到节点：
+
[source,terminal]
----
$ oc get nodes -l <key>=<value>,<key>=<value>
----
+
例如：
+
[source,terminal]
----
$ oc get nodes -l type=user-node,region=east
----
+
.输出示例：
[source,terminal]
----
NAME                                       STATUS   ROLES    AGE   VERSION
ci-ln-l8nry52-f76d1-hl7m7-worker-b-tgq49   Ready    worker   17m   v1.23.0
----
