// Module included in the following assemblies:
//
// * networking/network_policy/editing-network-policy.adoc

:name: network
:role: admin
ifeval::[{product-version} >= 4.6]
:ovn:
endif::[]
ifeval::["{context}" == "configuring-multi-network-policy"]
:multi:
:name: multi-network
:role: cluster-admin
endif::[]

:_content-type: PROCEDURE
[id="nw-networkpolicy-edit_{context}"]
= 编辑网络策略

您可以编辑命名空间中的网络策略。

[注意]
====
如果使用具有 `cluster-admin` 角色的用户登录，则可以在集群中的任何命名空间中编辑网络策略。
====


.先决条件

* 集群使用支持 `NetworkPolicy` 对象的集群网络供应商，如设置了 `mode: NetworkPolicy` 的 OpenShift SDN 网络供应商。此模式是 OpenShift SDN 的默认模式。
* 已安装 Uccp CLI (`oc`).
* 您可以使用具有 admin 权限的用户登陆到集群。
* 您在网络策略所在的命名空间中。

.流程

. 可选： 要列出一个命名空间中的网络策略对象，请输入以下命令：
+
[source,terminal,subs="attributes+"]
----
$ oc get {name}policy
----
+
--
其中：

`<namespace>`:: 可选： 如果对象在与当前命名空间不同的命名空间中定义，使用它来指定命名空间。
--

. 编辑网络策略对象。

** 如果您在文件中保存了网络策略定义，请编辑该文件并进行必要的更改，然后输入以下命令。
+
[source,terminal]
----
$ oc apply -n <namespace> -f <policy_file>.yaml
----
+
--
其中：

`<namespace>`:: 可选： 如果对象在与当前命名空间不同的命名空间中定义，使用它来指定命名空间。
`<policy_file>`:: 指定包含网络策略的文件的名称。
--

** 如果您需要直接更新网络策略对象，请输入以下命令：
+
[source,terminal,subs="attributes+"]
----
$ oc edit {name}policy <policy_name> -n <namespace>
----
+
--
其中：

`<policy_name>`:: 指定网络策略的名称。
`<namespace>`:: 可选： 如果对象在与当前命名空间不同的命名空间中定义，使用它来指定命名空间。
--

. 确认网络策略对象已更新。
+
[source,terminal,subs="attributes+"]
----
$ oc describe {name}policy <policy_name> -n <namespace>
----
+
--
其中：

`<policy_name>`:: 指定网络策略的名称。
`<namespace>`:: 可选： 如果对象在与当前命名空间不同的命名空间中定义，使用它来指定命名空间。
--

[注意]
====
如果您使用 `cluster-admin` 权限登录到 web 控制台，您可以选择在集群中的任何命名空间中以 YAML 或通过 *Actions* 菜单从 web 控制台中的策略编辑网络策略。
====
