:_content-type: PROCEDURE
[id="odc-deploying-java-applications_{context}"]
= 上传 JAR 文件以轻松部署 Java 应用程序

	您可以使用 *开发者* 视角的 *拓扑* 视图中的 JAR 文件来部署 Java 应用程序。您可以使用以下选项上传 JAR 文件：

* 导航到 *开发者* 视角 的 *+添加* 视图，再单击 *来自本地机器* 标题中的 *上传 JAR* 文件。浏览并选择您的 JAR 文件，或者拖放 JAR 文件以部署您的应用。

* 进入 *拓扑* 视图并使用 *上传 JAR* 文件 选项，或者拖放 JAR 文件来部署应用程序。

* 使用 *拓扑* 视图中的 上下文 菜单，然后使用 *上传 JAR* 文件选项上传 JAR 文件以部署应用程序。

使用以下说明在 *拓扑* 视图中上传 JAR 文件来部署 Java 应用程序：

.流程

. 使用以下说明在 *拓扑* 视图中上传 JAR 文件来部署 Java 应用程序：

. 将鼠标悬停在 *添加至项目* 菜单上，以查看菜单选项，然后选择 *上传 JAR* 文件选项以查看 *上传 JAR* 文件表单。或者，您可以在 *拓扑* 视图中拖放 JAR 文件。

. 在 *JAR 文件 字段中，浏览本地计算机上所需的 JAR 文件并上传该文件。或者，您可以将 JAR 文件拖放到字段。如果将不兼容的文件类型拖放到 拓扑 *视图中*，则右上角会显示一个警报。如果上传表单的字段中丢弃了不兼容的文件类型，则会显示字段错误。

. 您可以进一步指定可选的 Java 命令来自定义部署的应用程序。默认选择 *运行时图标* 和 *构建器镜像*。如果没有自动探测到构建器镜像，请选择一个构建器镜像。如果需要，您可以使用 *构建器镜像版本* 下拉列表来更改版本。

. 在可选的 *应用程序 字段中输入应用程序的唯一名称作为资源标记。

. 在 *名称* 字段中输入唯一组件名称来命名关联的资源。

. 在 *资源* 字段中，为您的应用程序选择资源类型。

. 在 *高级选项* 中，点 *创建应用程序的路由* 配置您部署的应用程序的公共 URL。

. 单击 *创建* 以部署应用。用户会看到一个切换通知，通知 JAR 文件正在上传，这个过程会花费一段时间。相关通知还包括用于查看构建日志的链接。

+
[注意]
====
如果用户尝试在构建运行时关闭浏览器标签页，系统会显示一个 Web 警报，询问用户是否真正想离开页面。
====

上传 JAR 文件并部署应用后，您可以在 *拓扑* 视图中看到部署。 
