////
This module included in the following assemblies:
-service_mesh/v2x/ossm-traffic-manage.adoc
////
:_content-type: PROCEDURE
[id="ossm-config-disable-networkpolicy_{context}"]
= Disabling automatic NetworkPolicy creation

如果要禁用 `NetworkPolicy` 资源自动创建和管理，例如强制实现公司安全策略，或者允许直接访问网格中的 pod，您可以这样做。您可以编辑 `ServiceMeshControlPlane` 并将 `spec.security.manageNetworkPolicy` t设置为 `false`.

[NOTE]
====
当您禁用了 spec.security.manageNetworkPolicy，Red Hat OpenShift Service Mesh 不会创建 *任何* `NetworkPolicy` 对象。系统管理员负责管理网络并修复可能导致的任何问题。
====

.先决条件

* 安装了 {SMProductName} Operator version 2.1.1 
* `ServiceMeshControlPlane` 资源更新至 2.1 。

.流程

. 在 {product-title} web 控制台中，点击 *Operators* -> *安装的 Operators*。

. 从  *项目* 菜单中选择安装 {SMProductShortName} control plane 的项目，如 `istio-system`。

. 点 {SMProductName} Operator。 在  *Istio Service Mesh Control Plane* 栏中，点 `ServiceMeshControlPlane` 的名称，如 `basic-install`。

. 在 *Create ServiceMeshControlPlane Details* 页中，点 `YAML` 修改您的配置。

. 将 `ServiceMeshControlPlane`  字段 `spec.security.manageNetworkPolicy` 设置为 `false`，如下例所示。
+
[source,yaml]
----
apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
spec:
  security:
      manageNetworkPolicy: false
----
+
. 点 *保存*.
