// Module included in the following assemblies:
//
// * post_installation_configuration/machine-configuration-tasks.adoc

:_content-type: PROCEDURE
[id="rhcos-enabling-multipath-day-2_{context}"]
= 在 Uswift 上启用带有内核参数的多路径

UnionTech Enterprise Linux Uswift (Uswift) 支持主磁盘上的多路径，允许对硬件故障进行更强大的弹性，以实现更高的主机可用性。通过机器配置激活多路径，提供安装后支持。

[重要:]
====
对于在 统信容器云管理平台 4.8 或更高版本中置备的节点，推荐在安装过程中启用多路径。在任何 I/O 到未优化路径会导致 I/O 系统错误的设置中，您必须在安装时启用多路径。有关在安装过程中启用多路径的更多信息，请参阅 _在裸机上安装_ 中的 "使用 Uswift 上内核参数启用多路径"。
====


.先决条件
* 您有一个正在运行的 统信容器云管理平台 集群，它使用版本 1.2或更高版本。
* 您以具有管理特权的用户身份登录集群。

.流程

. 要在 control plane 节点上启用多路径安装后：

* 创建机器配置文件，如 `99-master-kargs-mpath.yaml`，该文件指示集群添加 `master` 标签并标识多路径内核参数，例如：
+
[source,yaml]
----
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: "master"
  name: 99-master-kargs-mpath
spec:
  kernelArguments:
    - 'rd.multipath=default'
    - 'root=/dev/disk/by-label/dm-mpath-root'
----

. 在 worker 节点上启用多路径安装后：

* 创建机器配置文件，如 `99-worker-kargs-mpath.yaml`，该文件指示集群添加 `worker` 标签并标识多路径内核参数，例如：
+
[source,yaml]
----
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: "worker"
  name: 99-worker-kargs-mpath
spec:
  kernelArguments:
    - 'rd.multipath=default'
    - 'root=/dev/disk/by-label/dm-mpath-root'
----

. 使用之前创建的 master 或 worker YAML 文件创建新机器配置：
+
[source,terminal]
----
$ oc create -f ./99-worker-kargs-mpath.yaml
----

. 检查机器配置以查看是否添加了新配置：
+
[source,terminal]
----
$ oc get MachineConfig
----
+
.输出示例
[source,terminal]
----
NAME                                               GENERATEDBYCONTROLLER                      IGNITIONVERSION   AGE
00-master                                          52dd3ba6a9a527fc3ab42afac8d12b693534c8c9   3.2.0             33m
00-worker                                          52dd3ba6a9a527fc3ab42afac8d12b693534c8c9   3.2.0             33m
01-master-container-runtime                        52dd3ba6a9a527fc3ab42afac8d12b693534c8c9   3.2.0             33m
01-master-kubelet                                  52dd3ba6a9a527fc3ab42afac8d12b693534c8c9   3.2.0             33m
01-worker-container-runtime                        52dd3ba6a9a527fc3ab42afac8d12b693534c8c9   3.2.0             33m
01-worker-kubelet                                  52dd3ba6a9a527fc3ab42afac8d12b693534c8c9   3.2.0             33m
99-master-generated-registries                     52dd3ba6a9a527fc3ab42afac8d12b693534c8c9   3.2.0             33m
99-master-ssh                                                                                 3.2.0             40m
99-worker-generated-registries                     52dd3ba6a9a527fc3ab42afac8d12b693534c8c9   3.2.0             33m
99-worker-kargs-mpath                              52dd3ba6a9a527fc3ab42afac8d12b693534c8c9   3.2.0             105s
99-worker-ssh                                                                                 3.2.0             40m
rendered-master-23e785de7587df95a4b517e0647e5ab7   52dd3ba6a9a527fc3ab42afac8d12b693534c8c9   3.2.0             33m
rendered-worker-5d596d9293ca3ea80c896a1191735bb1   52dd3ba6a9a527fc3ab42afac8d12b693534c8c9   3.2.0             33m
----

. 检查节点：
+
[source,terminal]
----
$ oc get nodes
----
+
.输出示例
[source,terminal]
----
NAME                           STATUS                     ROLES    AGE   VERSION
ip-10-0-136-161.ec2.internal   Ready                      worker   28m   v1.23.0
ip-10-0-136-243.ec2.internal   Ready                      master   34m   v1.23.0
ip-10-0-141-105.ec2.internal   Ready,SchedulingDisabled   worker   28m   v1.23.0
ip-10-0-142-249.ec2.internal   Ready                      master   34m   v1.23.0
ip-10-0-153-11.ec2.internal    Ready                      worker   28m   v1.23.0
ip-10-0-153-150.ec2.internal   Ready                      master   34m   v1.23.0
----
+
您可以发现，在应用更改时每个 worker 节点上的调度都会被禁用。

. 前往其中一个 worker 节点并列出内核命令行参数（主机上的 `/proc/cmdline` 中），以检查内核参数确实已发挥作用：
+
[source,terminal]
----
$ oc debug node/ip-10-0-141-105.ec2.internal
----
+
.输出示例
[source,terminal]
----
Starting pod/ip-10-0-141-105ec2internal-debug ...
To use host binaries, run `chroot /host`

sh-4.2# cat /host/proc/cmdline
...
rd.multipath=default root=/dev/disk/by-label/dm-mpath-root
...

sh-4.2# exit
----
+
您应看到添加的内核参数。
