// Module is included in the following assemblies:
//
// * serverless/serverless-tracing.adoc

:_content-type: PROCEDURE
[id="serverless-open-telemetry_{context}"]
=  使用 统信容器云管理平台分布式追踪 启用分布式追踪

{DTProductName} 由几个组件组成，它们一起收集、存储和显示追踪数据。您可以使用统信容器云管理平台无服务的统信容器云管理平台分布式追踪 监控无服务器应用程序并进行故障排除。

.先决条件

* 您可以访问具有集群管理员权限的  {product-title} 帐户。
* 还没有安装  统信容器云管理平台无服务扩展组件、Knative Serving 和 Knative Eventing。这些需要在统信容器云管理平台分布式追踪安装后安装。
* 您已按照统信容器云管理平台分布式追踪文档安装了统信容器云管理平台分布式追踪
* 已安装 Uccps CLI (`oc`).
* 您已创建了一个项目，或者具有适当的角色和权限访问项目，以便在 {product-title} 中创建应用程序和其他工作负载。

.流程

. 创建 `OpenTelemetryCollector` 自定义资源 (CR) ：
+
.OpenTelemetryCollector CR 示例
[source,yaml]
----
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: cluster-collector
  namespace: <namespace>
spec:
  mode: deployment
  config: |
    receivers:
      zipkin:
    processors:
    exporters:
      jaeger:
        endpoint: jaeger-all-in-one-inmemory-collector-headless.tracing-system.svc:14250
        tls:
          ca_file: "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
      logging:
    service:
      pipelines:
        traces:
          receivers: [zipkin]
          processors: []
          exporters: [jaeger, logging]
----

. 验证有两个 pod 在安装了统信容器云管理平台分布式追踪的命名空间中运行：
+
[source,terminal]
----
$ oc get pods -n <namespace>
----
+
.输出示例
[source,terminal]
----
NAME                                          READY   STATUS    RESTARTS   AGE
cluster-collector-collector-85c766b5c-b5g99   1/1     Running   0          5m56s
jaeger-all-in-one-inmemory-ccbc9df4b-ndkl5    2/2     Running   0          15m
----

. 验证是否已创建以下无头服务：
+
[source,terminal]
----
$ oc get svc -n <namespace> | grep headless
----
+
.输出示例
[source,terminal]
----
cluster-collector-collector-headless            ClusterIP   None             <none>        9411/TCP                                 7m28s
jaeger-all-in-one-inmemory-collector-headless   ClusterIP   None             <none>        9411/TCP,14250/TCP,14267/TCP,14268/TCP   16m
----
+
这些服务用于配置 Jaeger、Knative Serving 和 Knative Eventing。Jaeger 服务的名称可能会有所不同。

. 按照安装统信容器云管理平台无服务扩展组件文档安装统信容器云管理平台无服务扩展组件

. 通过创建以下 `KnativeServing`  CR 来安装 Knative Serving：
+
.KnativeServing CR 示例
[source,yaml]
----
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
    name: knative-serving
    namespace: knative-serving
spec:
  config:
    tracing:
      backend: "zipkin"
      zipkin-endpoint: "http://cluster-collector-collector-headless.tracing-system.svc:9411/api/v2/spans"
      debug: "false"
      sample-rate: "0.1" <1>
----
<1> `sample-rate` 定义抽样概率。 `sample-rate: "0.1"` 表示在 10 个 trace 中会抽样 1 个。

. 通过创建以下 KnativeEventing CR 来安装 `KnativeEventing` ：
+
.Example KnativeEventing CR
[source,yaml]
----
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeEventing
metadata:
    name: knative-eventing
    namespace: knative-eventing
spec:
  config:
    tracing:
      backend: "zipkin"
      zipkin-endpoint: "http://cluster-collector-collector-headless.tracing-system.svc:9411/api/v2/spans"
      debug: "false"
      sample-rate: "0.1" <1>
----
<1> `sample-rate` 定义抽样概率。 `sample-rate: "0.1"` 表示在 10 个 trace 中会抽样 1 个。

. 创建 Knative 服务：
+
.服务示例
[source,yaml]
----
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-go
spec:
  template:
    metadata:
      labels:
        app: helloworld-go
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/target: "1"
    spec:
      containers:
      - image: quay.io/openshift-knative/helloworld:v1.2
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "200m"
        env:
        - name: TARGET
          value: "Go Sample v1"
----

. 向服务发出一些请求：
+
.HTTPS 请求示例
[source,terminal]
----
$ curl https://helloworld-go.example.com
----

. 获取 Jaeger web 控制台的 URL：
+
.示例命令
[source,terminal]
----
$ oc get route jaeger-all-in-one-inmemory  -o jsonpath='{.spec.host}' -n <namespace>
----
+
现在，您可以使用 Jaeger 控制台检查 trace。
