// Module included in the following assemblies:
//
// * /serverless/develop/serverless-custom-event-sources.adoc

:_content-type: PROCEDURE
[id="serverless-sinkbinding-yaml_{context}"]
= 使用 YAML 创建接收器绑定
使用 YAML 文件创建 Knative 资源使用声明性 API，它允许您以可重复的方式描述事件源。要使用 YAML 创建接收器绑定，您必须创建一个 YAML 文件来定义 `SinkBinding` 对象，然后使用 `oc apply`  命令应用它。

.先决条件

* 在集群中安装了 {ServerlessOperatorName}, Knative Serving 和 Knative Eventing。
* 安装 Uccps CLI (`oc`).
* 您已创建了一个项目，或者具有适当的角色和权限访问项目，以便在 {product-title} 中创建应用程序和其他工作负载。

.流程

. 要检查接收器绑定是否已正确设置，请创建一个 Knative 事件显示服务或事件接收器，在日志中转储传入的信息。

.. 创建服务 YAML 文件：
+
.服务 YAML 文件示例
[source,yaml]
----
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-display
spec:
  template:
    spec:
      containers:
        - image: quay.io/openshift-knative/knative-eventing-sources-event-display:latest
----
.. 创建服务：
+
[source,terminal]
----
$ oc apply -f <filename>
----

. 创建将事件定向到该服务的接收器绑定实例。

.. 创建接收器绑定 YAML 文件：
+
.服务 YAML 文件示例
[source,yaml]
----
apiVersion: sources.knative.dev/v1alpha1
kind: SinkBinding
metadata:
  name: bind-heartbeat
spec:
  subject:
    apiVersion: batch/v1
    kind: Job <1>
    selector:
      matchLabels:
        app: heartbeat-cron

  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
----
<1> 在本例中，任何具有标签 `app: heartbeat-cron` 的作业都将被绑定到事件 sink。

.. 创建接收器绑定：
+
[source,terminal]
----
$ oc apply -f <filename>
----

. 创建 CronJob 对象。

.. 创建 cron 任务 YAML 文件：
+
.Cron Job YAML 文件示例
[source,yaml]
----
apiVersion: batch/v1
kind: CronJob
metadata:
  name: heartbeat-cron
spec:
  # Run every minute
  schedule: "* * * * *"
  jobTemplate:
    metadata:
      labels:
        app: heartbeat-cron
        bindings.knative.dev/include: "true"
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: single-heartbeat
              image: quay.io/openshift-knative/heartbeats:latest
              args:
                - --period=1
              env:
                - name: ONE_SHOT
                  value: "true"
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
----
+
[IMPORTANT]
====
要使用接收器绑定，您必须手动在 Knative 资源中添加 `bindings.knative.dev/include=true` 标签

例如，要将此标签添加到 `CronJob` 资源，请将以下行添加到 `Job` 资源 YAML 定义中：

[source,yaml]
----
  jobTemplate:
    metadata:
      labels:
        app: heartbeat-cron
        bindings.knative.dev/include: "true"
----

====
+
.. 创建 cron job：
+
[source,terminal]
----
$ oc apply -f <filename>
----

. 输入以下命令并检查输出，检查是否正确映射了控制器：
+
[source,terminal]
----
$ oc get sinkbindings.sources.knative.dev bind-heartbeat -oyaml
----
+
.输出示例
[source,yaml]
----
spec:
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
      namespace: default
  subject:
    apiVersion: batch/v1
    kind: Job
    namespace: default
    selector:
      matchLabels:
        app: heartbeat-cron
----

.验证

您可以通过查看消息 dumper 功能日志，来验证 Kubernetes 事件是否已发送到 Knative 事件。

. 输入命令：
+
[source,terminal]
----
$ oc get pods
----

. 输入命令：
+
[source,terminal]
----
$ oc logs $(oc get pod -o name | grep event-display) -c user-container
----
+
.输出示例
[source,terminal]
----
☁️  cloudevents.Event
Validation: valid
Context Attributes,
  specversion: 1.0
  type: dev.knative.eventing.samples.heartbeat
  source: https://knative.dev/eventing-contrib/cmd/heartbeats/#event-test/mypod
  id: 2b72d7bf-c38f-4a98-a433-608fbcdd2596
  time: 2019-10-18T15:23:20.809775386Z
  contenttype: application/json
Extensions,
  beats: true
  heart: yes
  the: 42
Data,
  {
    "id": 1,
    "label": ""
  }
----
