// Module included in the following assemblies:
//
// * applications/quotas-setting-per-project.adoc

:_content-type: PROCEDURE
[id="setting-resource-quota-for-extended-resources_{context}"]
= 为扩展资源设定资源配额

扩展资源不允许过量使用资源，因此您必须在配额中为相同扩展资源指定 `requests` 和 `limits`。目前，扩展资源只允许使用带有前缀 `requests`. 配额项。以下是如何为 `CPU` 资源 cpu 设置资源配额的示例场景。

.流程

. 确定集群中某个节点中有多少 GPU 可用。例如：
+
[source,terminal]
----
# oc describe node ip-172-31-27-209.us-west-2.compute.internal | egrep 'Capacity|Allocatable|gpu'
----
+
.输出示例
[source,terminal]
----
 Capacity:
  cpu:                4
Allocatable:
  cpu:                3500m
  cpu                929m (26%)    0 (0%)
----
+
本例中有 4 个 CPU 可用。

. 在命名空间 demoproject中设置配额。本例中配额为 1：
+
[source,terminal]
----
# cat cpu-quota.yaml
----
+
.输出示例
[source,terminal]
----
apiVersion: v1
kind: ResourceQuota
metadata:
  name: cpu-quota
  namespace: demoproject
spec:
  hard:
    requests.cpu: 1
----

. 创建配额：
+
[source,terminal]
----
# oc create -f cpu-quota.yaml
----
+
.输出示例
[source,terminal]
----
resourcequota/cpu-quota created
----

. 验证命名空间是否设置了正确的配额：
+
[source,terminal]
----
# oc describe quota cpu-quota -n demoproject
----
+
.输出示例
[source,terminal]
----
Name:                    cpu-quota
Namespace:               demoproject
Resource                 Used  Hard
--------                 ----  ----
requests.cpu  			0     1
----

. 定义一个请求单个 GPU 的 Pod。以下示例定义文件名为 `cpu-pod.yaml`：
+
[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  generateName: cpu-pod-
  namespace: demoproject
spec:
  restartPolicy: OnFailure
  containers:
  - name: cpu-pod
    image: utccp/hello-utccp
    command: ["sleep"]
    args: ["infinity"]
    resources:
      limits:
        cpu: 1
----

. 创建 pod：
+
[source,terminal]
----
# oc create -f cpu-pod.yaml
----

. 验证 Pod 是否在运行：
+
[source,terminal]
----
# oc get pods
----
+
.输出示例
[source,terminal]
----
NAME              READY     STATUS      RESTARTS   AGE
cpu-pod-s46h7     1/1       Running     0          1m
----

. 验证配额计数器 Used 是否正确：
+
[source,terminal]
----
# oc describe quota cpu-quota -n demoproject
----
+
.输出示例
[source,terminal]
----
Name:                    cpu-quota
Namespace:               demoproject
Resource                 Used  Hard
--------                	 ----  ----
requests.cpu				  1     1
----

. 尝试在 `demoproject` 命名空间中创建第二个 CPU Pod。从技术上讲，该节点支持 4 个 CPU，因为它有 4 个 CPU：
+
[source,terminal]
----
# oc create -f cpu-pod.yaml
----
+
.输出示例
[source,terminal]
----
Error from server (Forbidden): error when creating "cpu-pod.yaml": pods "cpu-pod-rmwgv" is forbidden: exceeded quota: cpu-quota, requested: requests.cpu=1, used: requests.cpu=1, limited: requests.cpu=1
----
+
应该会显示此 *Forbidden* 错误消息，因为您有设为 1 个 CPU 的配额，但这一 Pod 试图分配第二个 CPU，而这超过了配额。
