// Module included in the following assemblies:
//
// * storage/understanding-persistent-storage.adoc

[id="persistent-volumes_{context}"]
= 持久性卷（PV）

每个 PV 都会包括一个 `spec` 和 `status`，它们分别代表卷的规格和状态，例如：

.`PersistentVolume` 对象定义示例
[source,yaml]
----
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001 <1>
spec:
  capacity:
    storage: 5Gi <2>
  accessModes:
    - ReadWriteOnce <3>
  persistentVolumeReclaimPolicy: Retain <4>
  ...
status:
  ...
----
<1> 持久性卷的名称。
<2> 卷可以使用的存储容量。
<3> 访问模式，用来指定读写权限及挂载权限。
<4> 重新声明策略，指定在资源被释放后如何处理它。

[id="types-of-persistent-volumes_{context}"]
== PV 类型

统信容器云管理平台支持以下 持久性卷插件：

// - GlusterFS
// - Ceph RBD
// - OpenStack Cinder
- Cinder
- Fibre Channel
- HostPath
- iSCSI
- Local volume
- NFS
- OpenStack Manila
- Uccp Container Storage
- VMware vSphere
// - Local


[id="pv-capacity_{context}"]
== 容量

一般情况下，一个持久性卷（PV）有特定的存储容量。这可以通过使用 PV 的 `capacity` 属性来设置。

	目前，存储容量是唯一可以设置或请求的资源。以后可能会包括 IOPS 、 throughput 等属性。

[id="pv-access-modes_{context}"]
== 访问模式

一个持久性卷可以以资源供应商支持的任何方式挂载到一个主机上。不同的供应商具有不同的功能，每个 PV 的访问模式可以被设置为特定卷支持的特定模式。例如：NFS 可以支持多个读写客户端，但一个特定的 NFS PV 可能会以只读方式导出。每个 PV 都有自己一组访问模式来描述指定的 PV 功能。

声明会与有类似访问模式的卷匹配。用来进行匹配的标准只包括访问模式和大小。声明的访问模式代表一个请求。比声明要求的条件更多的资源可能会匹配，而比要求的条件更少的资源则不会被匹配。例如：如果一个声明请求 RWO，但唯一可用卷是一个 NFS PV（RWO+ROX+RWX），则该声明与这个 NFS 相匹配，因为它支持 RWO。

系统会首先尝试直接匹配。卷的模式必须与您的请求匹配，或包含更多模式。大小必须大于或等于预期值。如果两个卷类型（如 NFS 和 iSCSI）有相同的访问模式，则一个要求这个模式的声明可能会与其中任何一个进行匹配。不同的卷类型之间没有匹配顺序，在同时匹配时也无法选择特定的一个卷类型。

所有有相同模式的卷都被分组，然后按大小（由小到大）进行排序。绑定程序会获取具有匹配模式的组群，并按容量顺序进行查找，直到找到一个大小匹配的项。

下表列出了访问模式：

.访问模式
[cols="1,1,3",options="header"]
|===
|访问模式 |CLI 缩写 |描述
|ReadWriteOnce
|`RWO`
|卷只可以被一个节点以读写模式挂载。
|ReadOnlyMany
|`ROX`
|卷可以被多个节点以只读形式挂载。
|ReadWriteMany
|`RWX`
|卷可以被多个节点以读写模式挂载。
|===

[重要]
====
卷访问模式是卷功能的描述。它们不会被强制限制。存储供应商会最终负责处理由于资源使用无效导致的运行时错误。

例如，NFS 提供 `ReadWriteOnce` 访问模式。如果您需要卷的访问模式为 ROX，则需要在声明中指定 `read-only` 。供应商中的错误会在运行时作为挂载错误显示。

iSCSI 和 Fibre Channel（光纤通道）卷目前没有隔离机制。您必须保证在同一时间点上只在一个节点使用这些卷。在某些情况下，比如对节点进行 drain 操作时，卷可以被两个节点同时使用。在对节点进行 drain 操作前，需要首先确定使用这些卷的 pod 已被删除。
====

.支持的 PV 访问模式
[cols=",^v,^v,^v", width="100%",options="header"]
|===
|Volume 插件  |ReadWriteOnce ^[1]^  |ReadOnlyMany  |ReadWriteMany
|Cinder  | ✅ | - |  -
|光纤通道  | ✅ | ✅ |  -
|HostPath  | ✅ | - |  -
|iSCSI  | ✅ | ✅ |  -
|Local volume | ✅ | - |  -
|NFS  | ✅ | ✅ | ✅
|OpenStack Manila  | - | - | ✅
|Uccp Container Storage  | ✅ | - | ✅
|VMware vSphere | ✅ | - | ✅ ^[3]^

|===
[.small]
--
1. ReadWriteOnce（RWO）卷不能挂载到多个节点上。如果节点失败，系统不允许将附加的 RWO 卷挂载到新节点上，因为它已经分配给了故障节点。如果因此遇到多附件错误消息，请强制在关闭或崩溃的节点上删除 pod，以避免关键工作负载中的数据丢失，例如在附加动态持久性卷时。
// GCE Persistent Disks, or Openstack Cinder PVs.
--
[id="pv-phase_{context}"]
== 阶段

卷可以处于以下几个阶段：

.卷阶段
[cols="1,2",options="header"]
|===

|阶段
|描述

|Available
|可用资源，还未绑定到任何声明

|Bound
|卷已绑定到一个声明。

|Released
|以前使用这个卷的声明已被删除，但该资源还没有被集群重新声明。

|Failed
|卷的自动重新声明失败。

|===

使用以下命令可以查看与 PV 绑定的 PVC 名称。

[source,terminal]
----
$ oc get pv <pv-claim>
----

[id="pv-mount-options_{context}"]
=== 挂载选项

您可以使用属性 `mountOptions` 在挂载 PV 时指定挂载选项。

例如：

.挂载选项示例
[source,yaml]
----
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  mountOptions: <1>
    - nfsvers=4.1
  nfs:
    path: /tmp
    server: 172.17.0.2
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: claim1
    namespace: default
----
<1> 在将 PV 挂载到磁盘时使用指定的挂载选项。

以下 PV 类型支持挂载选项：

- Cinder
- iSCSI
- Local volume
- NFS
- Uccp Container Storage（只限于 Ceph RBD）
- VMware vSphere

[注意]
====
HostPath PV 不支持挂载选项。
====
