// Module included in the following assemblies:
//
// * storage/understanding-persistent-storage.adoc

[id=lifecycle-volume-claim_{context}]
= 卷和声明的生命周期

PV 是集群中的资源。PVC 是对这些资源的请求，也是对该资源的声明检查。PV 和 PVC 之间的交互有以下生命周期。

[id="provisioning_{context}"]
== 置备存储

根据 PVC 中定义的开发人员的请求，集群管理员配置一个或者多个动态置备程序用来置备存储及一个匹配的 PV。

另外，集群管理员也可以预先创建多个 PV，它们包含了可用存储的详情。PV 存在于 API 中，且可以被使用。

[id="binding_{context}"]
== 绑定声明

当您创建 PVC 时，您会要求特定的存储量，指定所需的访问模式，并创建一个存储类来描述和分类存储。master 中的控制循环会随时检查是否有新的 PVC，并把新的 PVC 与一个适当的 PV 进行绑定。如果没有适当的 PV，则存储类的置备程序会创建一个适当的 PV。

所有 PV 的大小可能会超过 PVC 的大小。这在手动置备 PV 时尤为如此。要最小化超额，统信容器云管理平台将会把 PVC 绑定到匹配所有其他标准的最小 PV。

如果匹配的卷不存在，或者相关的置备程序无法创建所需的存储，则请求将会处于未绑定的状态。当出现了匹配的卷时，相应的声明就会与其绑定。例如：在一个集群中有多个手动置备的 50Gi 卷。它们无法和一个请求 100Gi 的 PVC 相匹配。当在这个集群中添加了一个 100Gi PV 时， PVC 就可以和这个 PV 绑定。

[id="using-pods_{context}"]
== 使用 pod 和声明的 PV

pod 使用声明（claim）作为卷。集群通过检查声明来找到绑定的卷，并为 pod 挂载相应的卷。对于那些支持多个访问模式的卷，您必须指定作为 pod 中的卷需要使用哪种模式。

一旦您的声明被绑定后，被绑定的 PV 就会专属于您，直到您不再需要它。您可以通过在 pod 的 volumes 定义中包括 `persistentVolumeClaim` 来调度 pod 并访问声明的 PV。

[注意]
====
如果将具有高文件数的持久性卷附加到 pod，则这些 pod 可能会失败，或者可能需要很长时间才能启动。
====


[id="pvcprotection_{context}"]
== 使用中的存储对象保护

使用中的存储对象保护功能确保了被 pod 使用的活跃的 PVC 以及与其绑定的 PV 不会从系统中移除，如果删除它们可能会导致数据丢失。

使用中的存储对象保护功能被默认启用。

[注意]
====
当使用 PVC 的 `Pod` 对象存在时，这个 PVC 被认为是被 Pod 使用的活跃的 PVC。
====

如果用户删除一个被 pod 使用的活跃的 PVC，这个 PVC 不会被立刻删除。这个删除过程会延迟到 PVC 不再被 pod 使用时才进行。另外，如果集群管理员删除了绑定到 PVC 的 PV，这个 PV 不会被立即删除。这个删除过程会延迟到 PV 不再绑定到 PVC 时才进行。


[id="releasing_{context}"]
== 释放持久性卷

当不再需要使用一个卷时，您可以从 API 中删除 PVC 对象，这样相应的资源就可以被重新声明。当声明被删除后，这个卷就被认为是已被释放，但它还不可以被另一个声明使用。这是因为之前声明者的数据仍然还保留在卷中，这些数据必须根据相关政策进行处理。

[id="reclaiming_{context}"]
== 持久性卷的重新声明策略

持久性卷重新声明（reclaim）策略指定了在卷被释放后集群可以如何使用它。卷重新声明政策包括 `Retain`、`Recycle` 或 `Delete`。

* `Retain` 策略可为那些支持它的卷插件手动重新声明资源。

* `Recycle` 策略在从其请求中释放后，将卷重新放入到未绑定的持久性卷池中。

[重要]
====
在统信容器云管理平台中， `Recycle` 重新声明策略已被弃用。我们推荐使用动态置备功能。
====

* `Delete` 策略删除统信容器云管理平台以及外部基础架构(如 AWS EBS 或者 VMware vSphere)中相关的存储资源中的 PersistentVolume。

[注意]
====
动态置备的卷总是被删除。
====
