// Module included in the following assemblies:
//
// * security/tls-profiles.adoc

ifeval::["{context}" == "tls-security-profiles"]
:tls:
endif::[]

:_content-type: PROCEDURE
[id="tls-profiles-kubelet-configuring_{context}"]
= 为 kubelet 配置 TLS 安全配置集

要在作为 HTTP 服务器时为 kubelet 配置 TLS 安全配置集，请创建一个 KubeletConfig 自定义资源（CR）来为特定节点指定预定义或自定义 TLS 安全配置集。如果没有配置 TLS 安全配置集，则默认 TLS 安全配置集为 Intermediate。


.在 worker 节点上配置 Old TLS 安全配置集的 KubeletConfig CR 示例
[source,yaml]
----
apiVersion: config.openshift.io/v1
kind: KubeletConfig
 ...
spec:
  tlsSecurityProfile:
    old: {}
    type: Old
  machineConfigPoolSelector:
    matchLabels:
      pools.operator.machineconfiguration.openshift.io/worker: ""
----

您可以在配置的节点上的 kubelet.conf 文件中看到配置 TLS 安全配置集的密码和最小 TLS 版本。

[重要]
====
kubelet 不支持 TLS 1.3，因为 Modern 配置集需要 TLS 1.3，因此不被支持。kubelet 将 Modern 配置集转换为 Intermediate。

kubelet 还会将 Old 或 Custom 配置集的 TLS 1.0 转换为 1.1，将 Custom 配置集的 TLS 1.3 转换为 1.2。
====

.先决条件

* 您可以使用具有 cluster-admin 角色的用户访问集群。

.流程

. 创建 KubeletConfig CR 来配置 TLS 安全配置集：
+
.Custom 配置集的 KubeletConfig CR 示例
[source,yaml]
----
apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: set-kubelet-tls-security-profile
spec:
  tlsSecurityProfile:
    type: Custom <1>
    custom: <2>
      ciphers: <3>
      - ECDHE-ECDSA-CHACHA20-POLY1305
      - ECDHE-RSA-CHACHA20-POLY1305
      - ECDHE-RSA-AES128-GCM-SHA256
      - ECDHE-ECDSA-AES128-GCM-SHA256
      minTLSVersion: VersionTLS11
  machineConfigPoolSelector:
    matchLabels:
      pools.operator.machineconfiguration.openshift.io/worker: "" <4>
----
+
<1> 指定 TLS 安全配置集类型 (`Old`, `Intermediate`, 或 `Custom`)。 默认值为 `Intermediate`.
<2> 为所选类型指定适当的字段：
* `old: {}`
* `intermediate: {}`
* `custom:`
<3> 对于 custom 类型，请指定 TLS 密码列表和最低接受的 TLS 版本。
<4> 可选：为您要应用 TLS 安全配置集的节点指定机器配置池标签。

. 创建 `KubeletConfig`` 对象：
+
[source,terminal]
----
$ oc create -f <filename>
----
+
根据集群中的 worker 节点数量，等待配置的节点被逐个重启。

.验证

要验证是否设置了配置集，请在节点处于 Ready 状态后执行以下步骤：

. 为配置的节点启动 debug 会话：
+
[source,terminal]
----
$ oc debug node/<node_name>
----

. 将 `/host` 设置为 debug shell 中的根目录：
+
[source,terminal]
----
sh-4.4# chroot /host
----

. 查看 `kubelet.conf` 文件：
+
[source,terminal]
----
sh-4.4# cat /etc/kubernetes/kubelet.conf
----
+
.输出示例
[source,terminal]
----
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
 ...
  "tlsCipherSuites": [
    "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
    "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
    "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
    "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
    "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
    "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256"
  ],
  "tlsMinVersion": "VersionTLS12",
----
