:_content-type: ASSEMBLY
[id="persistent-storage-vsphere"]
= VMware vSphere CSI Driver Operator
include::_attributes/common-attributes.adoc[]
:context: persistent-storage-csi-vsphere

toc::[]

== 概述

统信容器云管理平台可以使用 Container Storage Interface（CSI）VMDK（VMDK）卷的 VMware vSphere 驱动程序来置备持久性卷（PV）。

在使用 CSI Operator 和驱动程序时，建议先熟悉 持久性存储和配置 CSI 卷。

要创建挂载到 vSphere 存储资产中的 CSI 置备持久性卷(PV)，统信容器云管理平台在 `openshift-cluster-csi-drivers` 命名空间中默认安装 vSphere CSI Driver Operator 和 vSphere CSI 驱动程序。

* *vSphere CSI Driver Operator*: Operator 提供了一个称为 `thin-csi` 的存储类，您可以使用它来创建持久性卷声明(PVC)。vSphere CSI Driver Operator 支持动态卷置备，允许按需创建存储卷，使集群管理员无需预置备存储。

* *vSphere CSI driver*: 这个驱动程序可让您创建并挂载 vSphere PV。

//Please update driver version as needed with each major OCP release starting with 4.13.

//Listing the VMWare driver version here because it has a more variable set of features. The Operator version does not change independently (is parallel).

[重要]
====
统信容器云管理平台默认使用 in-tree（非 CSI）插件来置备 vSphere 存储。

在以后的统信容器云管理平台版本中，计划使用现有树内插件置备的卷迁移到对应的 CSI 驱动程序。CSI 自动迁移应该可以无缝进行。迁移不会改变您使用所有现有 API 对象的方式，如持久性卷、持久性卷声明和存储类。有关迁移的更多信息，请参阅 CSI 自动迁移。

完全迁移后，未来的统信容器云管理平台版本将最终删除树内插件。
====

[注意]
====
vSphere CSI 驱动程序支持动态和静态置备。当在 PV 规格中使用静态置备时，请不要在 `csi.volumeAttributes` 中使用键 `storage.kubernetes.io/csiProvisionerIdentity`，因为这个键代表动态置备的 PV。
====

include::modules/persistent-storage-csi-about.adoc[leveloffset=+1]

include::modules/persistent-storage-csi-vsphere-stor-policy.adoc[leveloffset=+1]

include::modules/vmware-csi-driver-reqs.adoc[leveloffset=+1]

include::modules/persistent-storage-csi-vsphere-rwx.adoc[leveloffset=+1]

include::modules/persistent-storage-csi-vsphere-install-issues.adoc[leveloffset=+1]

